/*
 * Copyright (C)  Eric Yang <eric_yang@accton.com>
 *
 * This module supports the accton fpga via pcie that read/write reg
 * mechanism to get OSFP/SFP status ...etc.
 * This includes the:
 *     Accton as1813_128o FPGA
 *
 * Copyright (C) 2017 Finisar Corp.
 *
 * This file is licensed under the terms of the GNU General Public
 * License version 2. This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */

#include <linux/module.h>
#include <linux/init.h>
#include <linux/slab.h>
#include <linux/device.h>
#include <linux/platform_device.h>
#include <linux/i2c.h>
#include <linux/mutex.h>
#include <linux/interrupt.h>
#include <linux/i2c-mux.h>
#include <linux/version.h>
#include <linux/stat.h>
#include <linux/hwmon-sysfs.h>
#include <linux/delay.h>
#include <linux/pci.h>
#include <linux/time64.h>

#define __STDC_WANT_LIB_EXT1__ 1
#include <linux/string.h>
#include <linux/platform_data/i2c-ocores.h>

/***********************************************
 *       variable define
 * *********************************************/
#define DRVNAME                        "as1813_128o_fpga"
#define OCORES_I2C_DRVNAME             "ocores-as1813"

#define PORT_NUM                       130 /* 128 OSFPs 2 SFPs*/
/*
 * PCIE BAR address
 */
#define BAR0_NUM                       0
#define FPGA_PCI_VENDOR_ID             0x10ee
#define FPGA_PCI_DEVICE_ID             0x7021
#define FPGA_PCIE_START_OFFSET         0x0000
#define FPGA_MAJOR_VER_REG             0x01
#define FPGA_MINOR_VER_REG             0x02
#define SPI_BUSY_MASK_CPLD             0x01
#define FPGA_BOARD_INFO_REG            (FPGA_PCIE_START_OFFSET + 0x00)
/* CPLD */
#define CPLD_PCIE_START_OFFSET         0x2000
/*FPGA SPI REG*/
#define SPI_MUX_REG                    0x2F00
#define SPI_BUSY_REG                   0x33

/*FPGA SPI*/
#define SPI_MUX_MB_CPLD0               0x0
#define SPI_MUX_MB_CPLD1               0x1
#define SPI_MUX_MEZZ_BOT_L             0x2
#define SPI_MUX_MEZZ_BOT_R             0x3
#define SPI_MUX_MEZZ_TOP_L             0x4
#define SPI_MUX_MEZZ_TOP_R             0x5


#define TRANSCEIVER_PRESENT_ATTR_ID(index)    MODULE_PRESENT_##index
#define TRANSCEIVER_LPMODE_ATTR_ID(index)     MODULE_LPMODE_##index
#define TRANSCEIVER_RESET_ATTR_ID(index)      MODULE_RESET_##index
#define TRANSCEIVER_TX_DISABLE_ATTR_ID(index) MODULE_TX_DISABLE_##index
#define TRANSCEIVER_TX_FAULT_ATTR_ID(index)   MODULE_TX_FAULT_##index
#define TRANSCEIVER_RX_LOS_ATTR_ID(index)     MODULE_RX_LOS_##index
/***********************************************
 *       macro define
 * *********************************************/
#define pcie_err(fmt, args...) \
        printk(KERN_ERR "["DRVNAME"]: " fmt " ", ##args)

#define pcie_info(fmt, args...) \
        printk(KERN_ERR "["DRVNAME"]: " fmt " ", ##args)


#define LOCK(lock)      \
do {                                                \
    spin_lock(lock);                                \
} while (0)

#define UNLOCK(lock)    \
do {                                                \
    spin_unlock(lock);                              \
} while (0)


/***********************************************
 *       structure & variable declare
 * *********************************************/
typedef struct pci_fpga_device_s {
    void  __iomem *data_base_addr0;
    struct pci_dev  *pci_dev;
    struct platform_device *fpga_i2c[PORT_NUM];
} pci_fpga_device_t;

/*fpga port status*/
struct as1813_128o_fpga_data {
    u8                  cpld_reg[2];
    unsigned long       last_updated;    /* In jiffies */
    pci_fpga_device_t   pci_fpga_dev;
};

static struct platform_device *pdev = NULL;
extern spinlock_t cpld_access_lock;
extern int wait_spi(u32 mask, u8 timeout);
extern void __iomem *spi_busy_reg;
extern void __iomem *spi_mux_reg;
/***********************************************
 *       enum define
 * *********************************************/
enum fpga_sysfs_attributes {
    /* transceiver attributes */
    TRANSCEIVER_PRESENT_ATTR_ID(1),
    TRANSCEIVER_PRESENT_ATTR_ID(2),
    TRANSCEIVER_PRESENT_ATTR_ID(3),
    TRANSCEIVER_PRESENT_ATTR_ID(4),
    TRANSCEIVER_PRESENT_ATTR_ID(5),
    TRANSCEIVER_PRESENT_ATTR_ID(6),
    TRANSCEIVER_PRESENT_ATTR_ID(7),
    TRANSCEIVER_PRESENT_ATTR_ID(8),
    TRANSCEIVER_PRESENT_ATTR_ID(9),
    TRANSCEIVER_PRESENT_ATTR_ID(10),
    TRANSCEIVER_PRESENT_ATTR_ID(11),
    TRANSCEIVER_PRESENT_ATTR_ID(12),
    TRANSCEIVER_PRESENT_ATTR_ID(13),
    TRANSCEIVER_PRESENT_ATTR_ID(14),
    TRANSCEIVER_PRESENT_ATTR_ID(15),
    TRANSCEIVER_PRESENT_ATTR_ID(16),
    TRANSCEIVER_PRESENT_ATTR_ID(17),
    TRANSCEIVER_PRESENT_ATTR_ID(18),
    TRANSCEIVER_PRESENT_ATTR_ID(19),
    TRANSCEIVER_PRESENT_ATTR_ID(20),
    TRANSCEIVER_PRESENT_ATTR_ID(21),
    TRANSCEIVER_PRESENT_ATTR_ID(22),
    TRANSCEIVER_PRESENT_ATTR_ID(23),
    TRANSCEIVER_PRESENT_ATTR_ID(24),
    TRANSCEIVER_PRESENT_ATTR_ID(25),
    TRANSCEIVER_PRESENT_ATTR_ID(26),
    TRANSCEIVER_PRESENT_ATTR_ID(27),
    TRANSCEIVER_PRESENT_ATTR_ID(28),
    TRANSCEIVER_PRESENT_ATTR_ID(29),
    TRANSCEIVER_PRESENT_ATTR_ID(30),
    TRANSCEIVER_PRESENT_ATTR_ID(31),
    TRANSCEIVER_PRESENT_ATTR_ID(32),
    TRANSCEIVER_PRESENT_ATTR_ID(33),
    TRANSCEIVER_PRESENT_ATTR_ID(34),
    TRANSCEIVER_PRESENT_ATTR_ID(35),
    TRANSCEIVER_PRESENT_ATTR_ID(36),
    TRANSCEIVER_PRESENT_ATTR_ID(37),
    TRANSCEIVER_PRESENT_ATTR_ID(38),
    TRANSCEIVER_PRESENT_ATTR_ID(39),
    TRANSCEIVER_PRESENT_ATTR_ID(40),
    TRANSCEIVER_PRESENT_ATTR_ID(41),
    TRANSCEIVER_PRESENT_ATTR_ID(42),
    TRANSCEIVER_PRESENT_ATTR_ID(43),
    TRANSCEIVER_PRESENT_ATTR_ID(44),
    TRANSCEIVER_PRESENT_ATTR_ID(45),
    TRANSCEIVER_PRESENT_ATTR_ID(46),
    TRANSCEIVER_PRESENT_ATTR_ID(47),
    TRANSCEIVER_PRESENT_ATTR_ID(48),
    TRANSCEIVER_PRESENT_ATTR_ID(49),
    TRANSCEIVER_PRESENT_ATTR_ID(50),
    TRANSCEIVER_PRESENT_ATTR_ID(51),
    TRANSCEIVER_PRESENT_ATTR_ID(52),
    TRANSCEIVER_PRESENT_ATTR_ID(53),
    TRANSCEIVER_PRESENT_ATTR_ID(54),
    TRANSCEIVER_PRESENT_ATTR_ID(55),
    TRANSCEIVER_PRESENT_ATTR_ID(56),
    TRANSCEIVER_PRESENT_ATTR_ID(57),
    TRANSCEIVER_PRESENT_ATTR_ID(58),
    TRANSCEIVER_PRESENT_ATTR_ID(59),
    TRANSCEIVER_PRESENT_ATTR_ID(60),
    TRANSCEIVER_PRESENT_ATTR_ID(61),
    TRANSCEIVER_PRESENT_ATTR_ID(62),
    TRANSCEIVER_PRESENT_ATTR_ID(63),
    TRANSCEIVER_PRESENT_ATTR_ID(64),
    TRANSCEIVER_PRESENT_ATTR_ID(65),
    TRANSCEIVER_PRESENT_ATTR_ID(66),
    TRANSCEIVER_PRESENT_ATTR_ID(67),
    TRANSCEIVER_PRESENT_ATTR_ID(68),
    TRANSCEIVER_PRESENT_ATTR_ID(69),
    TRANSCEIVER_PRESENT_ATTR_ID(70),
    TRANSCEIVER_PRESENT_ATTR_ID(71),
    TRANSCEIVER_PRESENT_ATTR_ID(72),
    TRANSCEIVER_PRESENT_ATTR_ID(73),
    TRANSCEIVER_PRESENT_ATTR_ID(74),
    TRANSCEIVER_PRESENT_ATTR_ID(75),
    TRANSCEIVER_PRESENT_ATTR_ID(76),
    TRANSCEIVER_PRESENT_ATTR_ID(77),
    TRANSCEIVER_PRESENT_ATTR_ID(78),
    TRANSCEIVER_PRESENT_ATTR_ID(79),
    TRANSCEIVER_PRESENT_ATTR_ID(80),
    TRANSCEIVER_PRESENT_ATTR_ID(81),
    TRANSCEIVER_PRESENT_ATTR_ID(82),
    TRANSCEIVER_PRESENT_ATTR_ID(83),
    TRANSCEIVER_PRESENT_ATTR_ID(84),
    TRANSCEIVER_PRESENT_ATTR_ID(85),
    TRANSCEIVER_PRESENT_ATTR_ID(86),
    TRANSCEIVER_PRESENT_ATTR_ID(87),
    TRANSCEIVER_PRESENT_ATTR_ID(88),
    TRANSCEIVER_PRESENT_ATTR_ID(89),
    TRANSCEIVER_PRESENT_ATTR_ID(90),
    TRANSCEIVER_PRESENT_ATTR_ID(91),
    TRANSCEIVER_PRESENT_ATTR_ID(92),
    TRANSCEIVER_PRESENT_ATTR_ID(93),
    TRANSCEIVER_PRESENT_ATTR_ID(94),
    TRANSCEIVER_PRESENT_ATTR_ID(95),
    TRANSCEIVER_PRESENT_ATTR_ID(96),
    TRANSCEIVER_PRESENT_ATTR_ID(97),
    TRANSCEIVER_PRESENT_ATTR_ID(98),
    TRANSCEIVER_PRESENT_ATTR_ID(99),
    TRANSCEIVER_PRESENT_ATTR_ID(100),
    TRANSCEIVER_PRESENT_ATTR_ID(101),
    TRANSCEIVER_PRESENT_ATTR_ID(102),
    TRANSCEIVER_PRESENT_ATTR_ID(103),
    TRANSCEIVER_PRESENT_ATTR_ID(104),
    TRANSCEIVER_PRESENT_ATTR_ID(105),
    TRANSCEIVER_PRESENT_ATTR_ID(106),
    TRANSCEIVER_PRESENT_ATTR_ID(107),
    TRANSCEIVER_PRESENT_ATTR_ID(108),
    TRANSCEIVER_PRESENT_ATTR_ID(109),
    TRANSCEIVER_PRESENT_ATTR_ID(110),
    TRANSCEIVER_PRESENT_ATTR_ID(111),
    TRANSCEIVER_PRESENT_ATTR_ID(112),
    TRANSCEIVER_PRESENT_ATTR_ID(113),
    TRANSCEIVER_PRESENT_ATTR_ID(114),
    TRANSCEIVER_PRESENT_ATTR_ID(115),
    TRANSCEIVER_PRESENT_ATTR_ID(116),
    TRANSCEIVER_PRESENT_ATTR_ID(117),
    TRANSCEIVER_PRESENT_ATTR_ID(118),
    TRANSCEIVER_PRESENT_ATTR_ID(119),
    TRANSCEIVER_PRESENT_ATTR_ID(120),
    TRANSCEIVER_PRESENT_ATTR_ID(121),
    TRANSCEIVER_PRESENT_ATTR_ID(122),
    TRANSCEIVER_PRESENT_ATTR_ID(123),
    TRANSCEIVER_PRESENT_ATTR_ID(124),
    TRANSCEIVER_PRESENT_ATTR_ID(125),
    TRANSCEIVER_PRESENT_ATTR_ID(126),
    TRANSCEIVER_PRESENT_ATTR_ID(127),
    TRANSCEIVER_PRESENT_ATTR_ID(128),
    TRANSCEIVER_PRESENT_ATTR_ID(129),
    TRANSCEIVER_PRESENT_ATTR_ID(130),
    /*Reset*/
    TRANSCEIVER_RESET_ATTR_ID(1),
    TRANSCEIVER_RESET_ATTR_ID(2),
    TRANSCEIVER_RESET_ATTR_ID(3),
    TRANSCEIVER_RESET_ATTR_ID(4),
    TRANSCEIVER_RESET_ATTR_ID(5),
    TRANSCEIVER_RESET_ATTR_ID(6),
    TRANSCEIVER_RESET_ATTR_ID(7),
    TRANSCEIVER_RESET_ATTR_ID(8),
    TRANSCEIVER_RESET_ATTR_ID(9),
    TRANSCEIVER_RESET_ATTR_ID(10),
    TRANSCEIVER_RESET_ATTR_ID(11),
    TRANSCEIVER_RESET_ATTR_ID(12),
    TRANSCEIVER_RESET_ATTR_ID(13),
    TRANSCEIVER_RESET_ATTR_ID(14),
    TRANSCEIVER_RESET_ATTR_ID(15),
    TRANSCEIVER_RESET_ATTR_ID(16),
    TRANSCEIVER_RESET_ATTR_ID(17),
    TRANSCEIVER_RESET_ATTR_ID(18),
    TRANSCEIVER_RESET_ATTR_ID(19),
    TRANSCEIVER_RESET_ATTR_ID(20),
    TRANSCEIVER_RESET_ATTR_ID(21),
    TRANSCEIVER_RESET_ATTR_ID(22),
    TRANSCEIVER_RESET_ATTR_ID(23),
    TRANSCEIVER_RESET_ATTR_ID(24),
    TRANSCEIVER_RESET_ATTR_ID(25),
    TRANSCEIVER_RESET_ATTR_ID(26),
    TRANSCEIVER_RESET_ATTR_ID(27),
    TRANSCEIVER_RESET_ATTR_ID(28),
    TRANSCEIVER_RESET_ATTR_ID(29),
    TRANSCEIVER_RESET_ATTR_ID(30),
    TRANSCEIVER_RESET_ATTR_ID(31),
    TRANSCEIVER_RESET_ATTR_ID(32),
    TRANSCEIVER_RESET_ATTR_ID(33),
    TRANSCEIVER_RESET_ATTR_ID(34),
    TRANSCEIVER_RESET_ATTR_ID(35),
    TRANSCEIVER_RESET_ATTR_ID(36),
    TRANSCEIVER_RESET_ATTR_ID(37),
    TRANSCEIVER_RESET_ATTR_ID(38),
    TRANSCEIVER_RESET_ATTR_ID(39),
    TRANSCEIVER_RESET_ATTR_ID(40),
    TRANSCEIVER_RESET_ATTR_ID(41),
    TRANSCEIVER_RESET_ATTR_ID(42),
    TRANSCEIVER_RESET_ATTR_ID(43),
    TRANSCEIVER_RESET_ATTR_ID(44),
    TRANSCEIVER_RESET_ATTR_ID(45),
    TRANSCEIVER_RESET_ATTR_ID(46),
    TRANSCEIVER_RESET_ATTR_ID(47),
    TRANSCEIVER_RESET_ATTR_ID(48),
    TRANSCEIVER_RESET_ATTR_ID(49),
    TRANSCEIVER_RESET_ATTR_ID(50),
    TRANSCEIVER_RESET_ATTR_ID(51),
    TRANSCEIVER_RESET_ATTR_ID(52),
    TRANSCEIVER_RESET_ATTR_ID(53),
    TRANSCEIVER_RESET_ATTR_ID(54),
    TRANSCEIVER_RESET_ATTR_ID(55),
    TRANSCEIVER_RESET_ATTR_ID(56),
    TRANSCEIVER_RESET_ATTR_ID(57),
    TRANSCEIVER_RESET_ATTR_ID(58),
    TRANSCEIVER_RESET_ATTR_ID(59),
    TRANSCEIVER_RESET_ATTR_ID(60),
    TRANSCEIVER_RESET_ATTR_ID(61),
    TRANSCEIVER_RESET_ATTR_ID(62),
    TRANSCEIVER_RESET_ATTR_ID(63),
    TRANSCEIVER_RESET_ATTR_ID(64),
    TRANSCEIVER_RESET_ATTR_ID(65),
    TRANSCEIVER_RESET_ATTR_ID(66),
    TRANSCEIVER_RESET_ATTR_ID(67),
    TRANSCEIVER_RESET_ATTR_ID(68),
    TRANSCEIVER_RESET_ATTR_ID(69),
    TRANSCEIVER_RESET_ATTR_ID(70),
    TRANSCEIVER_RESET_ATTR_ID(71),
    TRANSCEIVER_RESET_ATTR_ID(72),
    TRANSCEIVER_RESET_ATTR_ID(73),
    TRANSCEIVER_RESET_ATTR_ID(74),
    TRANSCEIVER_RESET_ATTR_ID(75),
    TRANSCEIVER_RESET_ATTR_ID(76),
    TRANSCEIVER_RESET_ATTR_ID(77),
    TRANSCEIVER_RESET_ATTR_ID(78),
    TRANSCEIVER_RESET_ATTR_ID(79),
    TRANSCEIVER_RESET_ATTR_ID(80),
    TRANSCEIVER_RESET_ATTR_ID(81),
    TRANSCEIVER_RESET_ATTR_ID(82),
    TRANSCEIVER_RESET_ATTR_ID(83),
    TRANSCEIVER_RESET_ATTR_ID(84),
    TRANSCEIVER_RESET_ATTR_ID(85),
    TRANSCEIVER_RESET_ATTR_ID(86),
    TRANSCEIVER_RESET_ATTR_ID(87),
    TRANSCEIVER_RESET_ATTR_ID(88),
    TRANSCEIVER_RESET_ATTR_ID(89),
    TRANSCEIVER_RESET_ATTR_ID(90),
    TRANSCEIVER_RESET_ATTR_ID(91),
    TRANSCEIVER_RESET_ATTR_ID(92),
    TRANSCEIVER_RESET_ATTR_ID(93),
    TRANSCEIVER_RESET_ATTR_ID(94),
    TRANSCEIVER_RESET_ATTR_ID(95),
    TRANSCEIVER_RESET_ATTR_ID(96),
    TRANSCEIVER_RESET_ATTR_ID(97),
    TRANSCEIVER_RESET_ATTR_ID(98),
    TRANSCEIVER_RESET_ATTR_ID(99),
    TRANSCEIVER_RESET_ATTR_ID(100),
    TRANSCEIVER_RESET_ATTR_ID(101),
    TRANSCEIVER_RESET_ATTR_ID(102),
    TRANSCEIVER_RESET_ATTR_ID(103),
    TRANSCEIVER_RESET_ATTR_ID(104),
    TRANSCEIVER_RESET_ATTR_ID(105),
    TRANSCEIVER_RESET_ATTR_ID(106),
    TRANSCEIVER_RESET_ATTR_ID(107),
    TRANSCEIVER_RESET_ATTR_ID(108),
    TRANSCEIVER_RESET_ATTR_ID(109),
    TRANSCEIVER_RESET_ATTR_ID(110),
    TRANSCEIVER_RESET_ATTR_ID(111),
    TRANSCEIVER_RESET_ATTR_ID(112),
    TRANSCEIVER_RESET_ATTR_ID(113),
    TRANSCEIVER_RESET_ATTR_ID(114),
    TRANSCEIVER_RESET_ATTR_ID(115),
    TRANSCEIVER_RESET_ATTR_ID(116),
    TRANSCEIVER_RESET_ATTR_ID(117),
    TRANSCEIVER_RESET_ATTR_ID(118),
    TRANSCEIVER_RESET_ATTR_ID(119),
    TRANSCEIVER_RESET_ATTR_ID(120),
    TRANSCEIVER_RESET_ATTR_ID(121),
    TRANSCEIVER_RESET_ATTR_ID(122),
    TRANSCEIVER_RESET_ATTR_ID(123),
    TRANSCEIVER_RESET_ATTR_ID(124),
    TRANSCEIVER_RESET_ATTR_ID(125),
    TRANSCEIVER_RESET_ATTR_ID(126),
    TRANSCEIVER_RESET_ATTR_ID(127),
    TRANSCEIVER_RESET_ATTR_ID(128),
    TRANSCEIVER_LPMODE_ATTR_ID(1),
    TRANSCEIVER_LPMODE_ATTR_ID(2),
    TRANSCEIVER_LPMODE_ATTR_ID(3),
    TRANSCEIVER_LPMODE_ATTR_ID(4),
    TRANSCEIVER_LPMODE_ATTR_ID(5),
    TRANSCEIVER_LPMODE_ATTR_ID(6),
    TRANSCEIVER_LPMODE_ATTR_ID(7),
    TRANSCEIVER_LPMODE_ATTR_ID(8),
    TRANSCEIVER_LPMODE_ATTR_ID(9),
    TRANSCEIVER_LPMODE_ATTR_ID(10),
    TRANSCEIVER_LPMODE_ATTR_ID(11),
    TRANSCEIVER_LPMODE_ATTR_ID(12),
    TRANSCEIVER_LPMODE_ATTR_ID(13),
    TRANSCEIVER_LPMODE_ATTR_ID(14),
    TRANSCEIVER_LPMODE_ATTR_ID(15),
    TRANSCEIVER_LPMODE_ATTR_ID(16),
    TRANSCEIVER_LPMODE_ATTR_ID(17),
    TRANSCEIVER_LPMODE_ATTR_ID(18),
    TRANSCEIVER_LPMODE_ATTR_ID(19),
    TRANSCEIVER_LPMODE_ATTR_ID(20),
    TRANSCEIVER_LPMODE_ATTR_ID(21),
    TRANSCEIVER_LPMODE_ATTR_ID(22),
    TRANSCEIVER_LPMODE_ATTR_ID(23),
    TRANSCEIVER_LPMODE_ATTR_ID(24),
    TRANSCEIVER_LPMODE_ATTR_ID(25),
    TRANSCEIVER_LPMODE_ATTR_ID(26),
    TRANSCEIVER_LPMODE_ATTR_ID(27),
    TRANSCEIVER_LPMODE_ATTR_ID(28),
    TRANSCEIVER_LPMODE_ATTR_ID(29),
    TRANSCEIVER_LPMODE_ATTR_ID(30),
    TRANSCEIVER_LPMODE_ATTR_ID(31),
    TRANSCEIVER_LPMODE_ATTR_ID(32),
    TRANSCEIVER_LPMODE_ATTR_ID(33),
    TRANSCEIVER_LPMODE_ATTR_ID(34),
    TRANSCEIVER_LPMODE_ATTR_ID(35),
    TRANSCEIVER_LPMODE_ATTR_ID(36),
    TRANSCEIVER_LPMODE_ATTR_ID(37),
    TRANSCEIVER_LPMODE_ATTR_ID(38),
    TRANSCEIVER_LPMODE_ATTR_ID(39),
    TRANSCEIVER_LPMODE_ATTR_ID(40),
    TRANSCEIVER_LPMODE_ATTR_ID(41),
    TRANSCEIVER_LPMODE_ATTR_ID(42),
    TRANSCEIVER_LPMODE_ATTR_ID(43),
    TRANSCEIVER_LPMODE_ATTR_ID(44),
    TRANSCEIVER_LPMODE_ATTR_ID(45),
    TRANSCEIVER_LPMODE_ATTR_ID(46),
    TRANSCEIVER_LPMODE_ATTR_ID(47),
    TRANSCEIVER_LPMODE_ATTR_ID(48),
    TRANSCEIVER_LPMODE_ATTR_ID(49),
    TRANSCEIVER_LPMODE_ATTR_ID(50),
    TRANSCEIVER_LPMODE_ATTR_ID(51),
    TRANSCEIVER_LPMODE_ATTR_ID(52),
    TRANSCEIVER_LPMODE_ATTR_ID(53),
    TRANSCEIVER_LPMODE_ATTR_ID(54),
    TRANSCEIVER_LPMODE_ATTR_ID(55),
    TRANSCEIVER_LPMODE_ATTR_ID(56),
    TRANSCEIVER_LPMODE_ATTR_ID(57),
    TRANSCEIVER_LPMODE_ATTR_ID(58),
    TRANSCEIVER_LPMODE_ATTR_ID(59),
    TRANSCEIVER_LPMODE_ATTR_ID(60),
    TRANSCEIVER_LPMODE_ATTR_ID(61),
    TRANSCEIVER_LPMODE_ATTR_ID(62),
    TRANSCEIVER_LPMODE_ATTR_ID(63),
    TRANSCEIVER_LPMODE_ATTR_ID(64),
    TRANSCEIVER_LPMODE_ATTR_ID(65),
    TRANSCEIVER_LPMODE_ATTR_ID(66),
    TRANSCEIVER_LPMODE_ATTR_ID(67),
    TRANSCEIVER_LPMODE_ATTR_ID(68),
    TRANSCEIVER_LPMODE_ATTR_ID(69),
    TRANSCEIVER_LPMODE_ATTR_ID(70),
    TRANSCEIVER_LPMODE_ATTR_ID(71),
    TRANSCEIVER_LPMODE_ATTR_ID(72),
    TRANSCEIVER_LPMODE_ATTR_ID(73),
    TRANSCEIVER_LPMODE_ATTR_ID(74),
    TRANSCEIVER_LPMODE_ATTR_ID(75),
    TRANSCEIVER_LPMODE_ATTR_ID(76),
    TRANSCEIVER_LPMODE_ATTR_ID(77),
    TRANSCEIVER_LPMODE_ATTR_ID(78),
    TRANSCEIVER_LPMODE_ATTR_ID(79),
    TRANSCEIVER_LPMODE_ATTR_ID(80),
    TRANSCEIVER_LPMODE_ATTR_ID(81),
    TRANSCEIVER_LPMODE_ATTR_ID(82),
    TRANSCEIVER_LPMODE_ATTR_ID(83),
    TRANSCEIVER_LPMODE_ATTR_ID(84),
    TRANSCEIVER_LPMODE_ATTR_ID(85),
    TRANSCEIVER_LPMODE_ATTR_ID(86),
    TRANSCEIVER_LPMODE_ATTR_ID(87),
    TRANSCEIVER_LPMODE_ATTR_ID(88),
    TRANSCEIVER_LPMODE_ATTR_ID(89),
    TRANSCEIVER_LPMODE_ATTR_ID(90),
    TRANSCEIVER_LPMODE_ATTR_ID(91),
    TRANSCEIVER_LPMODE_ATTR_ID(92),
    TRANSCEIVER_LPMODE_ATTR_ID(93),
    TRANSCEIVER_LPMODE_ATTR_ID(94),
    TRANSCEIVER_LPMODE_ATTR_ID(95),
    TRANSCEIVER_LPMODE_ATTR_ID(96),
    TRANSCEIVER_LPMODE_ATTR_ID(97),
    TRANSCEIVER_LPMODE_ATTR_ID(98),
    TRANSCEIVER_LPMODE_ATTR_ID(99),
    TRANSCEIVER_LPMODE_ATTR_ID(100),
    TRANSCEIVER_LPMODE_ATTR_ID(101),
    TRANSCEIVER_LPMODE_ATTR_ID(102),
    TRANSCEIVER_LPMODE_ATTR_ID(103),
    TRANSCEIVER_LPMODE_ATTR_ID(104),
    TRANSCEIVER_LPMODE_ATTR_ID(105),
    TRANSCEIVER_LPMODE_ATTR_ID(106),
    TRANSCEIVER_LPMODE_ATTR_ID(107),
    TRANSCEIVER_LPMODE_ATTR_ID(108),
    TRANSCEIVER_LPMODE_ATTR_ID(109),
    TRANSCEIVER_LPMODE_ATTR_ID(110),
    TRANSCEIVER_LPMODE_ATTR_ID(111),
    TRANSCEIVER_LPMODE_ATTR_ID(112),
    TRANSCEIVER_LPMODE_ATTR_ID(113),
    TRANSCEIVER_LPMODE_ATTR_ID(114),
    TRANSCEIVER_LPMODE_ATTR_ID(115),
    TRANSCEIVER_LPMODE_ATTR_ID(116),
    TRANSCEIVER_LPMODE_ATTR_ID(117),
    TRANSCEIVER_LPMODE_ATTR_ID(118),
    TRANSCEIVER_LPMODE_ATTR_ID(119),
    TRANSCEIVER_LPMODE_ATTR_ID(120),
    TRANSCEIVER_LPMODE_ATTR_ID(121),
    TRANSCEIVER_LPMODE_ATTR_ID(122),
    TRANSCEIVER_LPMODE_ATTR_ID(123),
    TRANSCEIVER_LPMODE_ATTR_ID(124),
    TRANSCEIVER_LPMODE_ATTR_ID(125),
    TRANSCEIVER_LPMODE_ATTR_ID(126),
    TRANSCEIVER_LPMODE_ATTR_ID(127),
    TRANSCEIVER_LPMODE_ATTR_ID(128),
    TRANSCEIVER_TX_DISABLE_ATTR_ID(129),
    TRANSCEIVER_TX_DISABLE_ATTR_ID(130),
    TRANSCEIVER_TX_FAULT_ATTR_ID(129),
    TRANSCEIVER_TX_FAULT_ATTR_ID(130),
    TRANSCEIVER_RX_LOS_ATTR_ID(129),
    TRANSCEIVER_RX_LOS_ATTR_ID(130),
};

/***********************************************
 *       function declare
 * *********************************************/
static ssize_t status_read(struct device *dev, struct device_attribute *da,
             char *buf);
static ssize_t status_write(struct device *dev, struct device_attribute *da,
            const char *buf, size_t count);

#define DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(index) \
    static SENSOR_DEVICE_ATTR(module_present_##index, S_IRUGO, status_read, NULL, MODULE_PRESENT_##index); \
    static SENSOR_DEVICE_ATTR(module_reset_##index, S_IRUGO|S_IWUSR, status_read, status_write, MODULE_RESET_##index); \
    static SENSOR_DEVICE_ATTR(module_lp_mode_##index, S_IRUGO|S_IWUSR, status_read, status_write, MODULE_LPMODE_##index)
#define DECLARE_TRANSCEIVER_ATTR(index) \
    &sensor_dev_attr_module_present_##index.dev_attr.attr, \
    &sensor_dev_attr_module_reset_##index.dev_attr.attr, \
    &sensor_dev_attr_module_lp_mode_##index.dev_attr.attr

/* transceiver attributes */
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(1);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(2);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(3);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(4);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(5);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(6);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(7);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(8);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(9);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(10);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(11);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(12);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(13);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(14);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(15);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(16);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(17);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(18);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(19);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(20);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(21);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(22);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(23);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(24);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(25);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(26);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(27);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(28);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(29);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(30);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(31);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(32);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(33);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(34);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(35);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(36);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(37);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(38);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(39);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(40);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(41);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(42);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(43);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(44);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(45);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(46);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(47);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(48);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(49);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(50);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(51);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(52);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(53);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(54);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(55);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(56);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(57);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(58);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(59);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(60);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(61);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(62);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(63);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(64);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(65);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(66);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(67);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(68);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(69);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(70);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(71);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(72);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(73);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(74);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(75);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(76);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(77);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(78);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(79);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(80);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(81);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(82);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(83);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(84);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(85);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(86);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(87);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(88);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(89);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(90);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(91);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(92);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(93);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(94);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(95);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(96);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(97);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(98);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(99);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(100);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(101);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(102);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(103);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(104);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(105);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(106);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(107);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(108);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(109);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(110);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(111);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(112);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(113);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(114);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(115);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(116);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(117);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(118);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(119);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(120);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(121);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(122);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(123);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(124);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(125);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(126);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(127);
DECLARE_TRANSCEIVER_SENSOR_DEVICE_ATTR(128);
static SENSOR_DEVICE_ATTR(module_present_129, S_IRUGO, status_read, NULL, MODULE_PRESENT_129);
static SENSOR_DEVICE_ATTR(module_present_130, S_IRUGO, status_read, NULL, MODULE_PRESENT_130);
static SENSOR_DEVICE_ATTR(module_tx_disable_129, S_IRUGO|S_IWUSR, status_read,
                          status_write, MODULE_TX_DISABLE_129);
static SENSOR_DEVICE_ATTR(module_tx_disable_130, S_IRUGO|S_IWUSR, status_read,
                          status_write, MODULE_TX_DISABLE_130);
static SENSOR_DEVICE_ATTR(module_tx_fault_129, S_IRUGO, status_read, NULL, MODULE_TX_FAULT_129);
static SENSOR_DEVICE_ATTR(module_tx_fault_130, S_IRUGO, status_read, NULL, MODULE_TX_FAULT_130);
static SENSOR_DEVICE_ATTR(module_rx_los_129, S_IRUGO, status_read, NULL, MODULE_RX_LOS_129);
static SENSOR_DEVICE_ATTR(module_rx_los_130, S_IRUGO, status_read, NULL, MODULE_RX_LOS_130);

static struct attribute *fpga_transceiver_attributes[] = {
    DECLARE_TRANSCEIVER_ATTR(1),
    DECLARE_TRANSCEIVER_ATTR(2),
    DECLARE_TRANSCEIVER_ATTR(3),
    DECLARE_TRANSCEIVER_ATTR(4),
    DECLARE_TRANSCEIVER_ATTR(5),
    DECLARE_TRANSCEIVER_ATTR(6),
    DECLARE_TRANSCEIVER_ATTR(7),
    DECLARE_TRANSCEIVER_ATTR(8),
    DECLARE_TRANSCEIVER_ATTR(9),
    DECLARE_TRANSCEIVER_ATTR(10),
    DECLARE_TRANSCEIVER_ATTR(11),
    DECLARE_TRANSCEIVER_ATTR(12),
    DECLARE_TRANSCEIVER_ATTR(13),
    DECLARE_TRANSCEIVER_ATTR(14),
    DECLARE_TRANSCEIVER_ATTR(15),
    DECLARE_TRANSCEIVER_ATTR(16),
    DECLARE_TRANSCEIVER_ATTR(17),
    DECLARE_TRANSCEIVER_ATTR(18),
    DECLARE_TRANSCEIVER_ATTR(19),
    DECLARE_TRANSCEIVER_ATTR(20),
    DECLARE_TRANSCEIVER_ATTR(21),
    DECLARE_TRANSCEIVER_ATTR(22),
    DECLARE_TRANSCEIVER_ATTR(23),
    DECLARE_TRANSCEIVER_ATTR(24),
    DECLARE_TRANSCEIVER_ATTR(25),
    DECLARE_TRANSCEIVER_ATTR(26),
    DECLARE_TRANSCEIVER_ATTR(27),
    DECLARE_TRANSCEIVER_ATTR(28),
    DECLARE_TRANSCEIVER_ATTR(29),
    DECLARE_TRANSCEIVER_ATTR(30),
    DECLARE_TRANSCEIVER_ATTR(31),
    DECLARE_TRANSCEIVER_ATTR(32),
    DECLARE_TRANSCEIVER_ATTR(33),
    DECLARE_TRANSCEIVER_ATTR(34),
    DECLARE_TRANSCEIVER_ATTR(35),
    DECLARE_TRANSCEIVER_ATTR(36),
    DECLARE_TRANSCEIVER_ATTR(37),
    DECLARE_TRANSCEIVER_ATTR(38),
    DECLARE_TRANSCEIVER_ATTR(39),
    DECLARE_TRANSCEIVER_ATTR(40),
    DECLARE_TRANSCEIVER_ATTR(41),
    DECLARE_TRANSCEIVER_ATTR(42),
    DECLARE_TRANSCEIVER_ATTR(43),
    DECLARE_TRANSCEIVER_ATTR(44),
    DECLARE_TRANSCEIVER_ATTR(45),
    DECLARE_TRANSCEIVER_ATTR(46),
    DECLARE_TRANSCEIVER_ATTR(47),
    DECLARE_TRANSCEIVER_ATTR(48),
    DECLARE_TRANSCEIVER_ATTR(49),
    DECLARE_TRANSCEIVER_ATTR(50),
    DECLARE_TRANSCEIVER_ATTR(51),
    DECLARE_TRANSCEIVER_ATTR(52),
    DECLARE_TRANSCEIVER_ATTR(53),
    DECLARE_TRANSCEIVER_ATTR(54),
    DECLARE_TRANSCEIVER_ATTR(55),
    DECLARE_TRANSCEIVER_ATTR(56),
    DECLARE_TRANSCEIVER_ATTR(57),
    DECLARE_TRANSCEIVER_ATTR(58),
    DECLARE_TRANSCEIVER_ATTR(59),
    DECLARE_TRANSCEIVER_ATTR(60),
    DECLARE_TRANSCEIVER_ATTR(61),
    DECLARE_TRANSCEIVER_ATTR(62),
    DECLARE_TRANSCEIVER_ATTR(63),
    DECLARE_TRANSCEIVER_ATTR(64),
    DECLARE_TRANSCEIVER_ATTR(65),
    DECLARE_TRANSCEIVER_ATTR(66),
    DECLARE_TRANSCEIVER_ATTR(67),
    DECLARE_TRANSCEIVER_ATTR(68),
    DECLARE_TRANSCEIVER_ATTR(69),
    DECLARE_TRANSCEIVER_ATTR(70),
    DECLARE_TRANSCEIVER_ATTR(71),
    DECLARE_TRANSCEIVER_ATTR(72),
    DECLARE_TRANSCEIVER_ATTR(73),
    DECLARE_TRANSCEIVER_ATTR(74),
    DECLARE_TRANSCEIVER_ATTR(75),
    DECLARE_TRANSCEIVER_ATTR(76),
    DECLARE_TRANSCEIVER_ATTR(77),
    DECLARE_TRANSCEIVER_ATTR(78),
    DECLARE_TRANSCEIVER_ATTR(79),
    DECLARE_TRANSCEIVER_ATTR(80),
    DECLARE_TRANSCEIVER_ATTR(81),
    DECLARE_TRANSCEIVER_ATTR(82),
    DECLARE_TRANSCEIVER_ATTR(83),
    DECLARE_TRANSCEIVER_ATTR(84),
    DECLARE_TRANSCEIVER_ATTR(85),
    DECLARE_TRANSCEIVER_ATTR(86),
    DECLARE_TRANSCEIVER_ATTR(87),
    DECLARE_TRANSCEIVER_ATTR(88),
    DECLARE_TRANSCEIVER_ATTR(89),
    DECLARE_TRANSCEIVER_ATTR(90),
    DECLARE_TRANSCEIVER_ATTR(91),
    DECLARE_TRANSCEIVER_ATTR(92),
    DECLARE_TRANSCEIVER_ATTR(93),
    DECLARE_TRANSCEIVER_ATTR(94),
    DECLARE_TRANSCEIVER_ATTR(95),
    DECLARE_TRANSCEIVER_ATTR(96),
    DECLARE_TRANSCEIVER_ATTR(97),
    DECLARE_TRANSCEIVER_ATTR(98),
    DECLARE_TRANSCEIVER_ATTR(99),
    DECLARE_TRANSCEIVER_ATTR(100),
    DECLARE_TRANSCEIVER_ATTR(101),
    DECLARE_TRANSCEIVER_ATTR(102),
    DECLARE_TRANSCEIVER_ATTR(103),
    DECLARE_TRANSCEIVER_ATTR(104),
    DECLARE_TRANSCEIVER_ATTR(105),
    DECLARE_TRANSCEIVER_ATTR(106),
    DECLARE_TRANSCEIVER_ATTR(107),
    DECLARE_TRANSCEIVER_ATTR(108),
    DECLARE_TRANSCEIVER_ATTR(109),
    DECLARE_TRANSCEIVER_ATTR(110),
    DECLARE_TRANSCEIVER_ATTR(111),
    DECLARE_TRANSCEIVER_ATTR(112),
    DECLARE_TRANSCEIVER_ATTR(113),
    DECLARE_TRANSCEIVER_ATTR(114),
    DECLARE_TRANSCEIVER_ATTR(115),
    DECLARE_TRANSCEIVER_ATTR(116),
    DECLARE_TRANSCEIVER_ATTR(117),
    DECLARE_TRANSCEIVER_ATTR(118),
    DECLARE_TRANSCEIVER_ATTR(119),
    DECLARE_TRANSCEIVER_ATTR(120),
    DECLARE_TRANSCEIVER_ATTR(121),
    DECLARE_TRANSCEIVER_ATTR(122),
    DECLARE_TRANSCEIVER_ATTR(123),
    DECLARE_TRANSCEIVER_ATTR(124),
    DECLARE_TRANSCEIVER_ATTR(125),
    DECLARE_TRANSCEIVER_ATTR(126),
    DECLARE_TRANSCEIVER_ATTR(127),
    DECLARE_TRANSCEIVER_ATTR(128),
    &sensor_dev_attr_module_present_129.dev_attr.attr,
    &sensor_dev_attr_module_present_130.dev_attr.attr,
    &sensor_dev_attr_module_tx_disable_129.dev_attr.attr,
    &sensor_dev_attr_module_tx_disable_130.dev_attr.attr,
    &sensor_dev_attr_module_tx_fault_129.dev_attr.attr,
    &sensor_dev_attr_module_tx_fault_130.dev_attr.attr,
    &sensor_dev_attr_module_rx_los_129.dev_attr.attr,
    &sensor_dev_attr_module_rx_los_130.dev_attr.attr,
    NULL
};

static const struct attribute_group fpga_port_stat_group = {
    .attrs = fpga_transceiver_attributes,
};

struct attribute_mapping {
    u16 reg;
    u16 spi_mux;
    u16 mask;
    u8 revert;
};

// Define an array of attribute mappings
static struct attribute_mapping attribute_mappings[] = {
    /*MEZZ TOP L*/
    [MODULE_PRESENT_1]   = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_L, 0x01 << 0, 1}, //PRESENT port1
    [MODULE_PRESENT_2]   = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_L, 0x01 << 1, 1}, //PRESENT port2
    [MODULE_PRESENT_9]   = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_L, 0x01 << 2, 1}, //PRESENT port9
    [MODULE_PRESENT_10]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_L, 0x01 << 3, 1}, //PRESENT port10
    [MODULE_PRESENT_17]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_L, 0x01 << 4, 1}, //PRESENT port17
    [MODULE_PRESENT_18]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_L, 0x01 << 5, 1}, //PRESENT port18
    [MODULE_PRESENT_25]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_L, 0x01 << 6, 1}, //PRESENT port25
    [MODULE_PRESENT_26]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_L, 0x01 << 7, 1}, //PRESENT port26
    [MODULE_PRESENT_33]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_L, 0x01 << 0, 1}, //PRESENT port33
    [MODULE_PRESENT_34]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_L, 0x01 << 1, 1}, //PRESENT port34
    [MODULE_PRESENT_41]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_L, 0x01 << 2, 1}, //PRESENT port41
    [MODULE_PRESENT_42]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_L, 0x01 << 3, 1}, //PRESENT port42
    [MODULE_PRESENT_49]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_L, 0x01 << 4, 1}, //PRESENT port49
    [MODULE_PRESENT_50]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_L, 0x01 << 5, 1}, //PRESENT port50
    [MODULE_PRESENT_57]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_L, 0x01 << 6, 1}, //PRESENT port57
    [MODULE_PRESENT_58]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_L, 0x01 << 7, 1}, //PRESENT port58
    [MODULE_RESET_1]     = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_L, 0x01 << 0, 1}, //RESET port1
    [MODULE_RESET_2]     = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_L, 0x01 << 1, 1}, //RESET port2
    [MODULE_RESET_9]     = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_L, 0x01 << 2, 1}, //RESET port9
    [MODULE_RESET_10]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_L, 0x01 << 3, 1}, //RESET port10
    [MODULE_RESET_17]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_L, 0x01 << 4, 1}, //RESET port17
    [MODULE_RESET_18]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_L, 0x01 << 5, 1}, //RESET port18
    [MODULE_RESET_25]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_L, 0x01 << 6, 1}, //RESET port25
    [MODULE_RESET_26]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_L, 0x01 << 7, 1}, //RESET port26
    [MODULE_RESET_33]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_L, 0x01 << 0, 1}, //RESET port33
    [MODULE_RESET_34]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_L, 0x01 << 1, 1}, //RESET port34
    [MODULE_RESET_41]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_L, 0x01 << 2, 1}, //RESET port41
    [MODULE_RESET_42]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_L, 0x01 << 3, 1}, //RESET port42
    [MODULE_RESET_49]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_L, 0x01 << 4, 1}, //RESET port49
    [MODULE_RESET_50]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_L, 0x01 << 5, 1}, //RESET port50
    [MODULE_RESET_57]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_L, 0x01 << 6, 1}, //RESET port57
    [MODULE_RESET_58]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_L, 0x01 << 7, 1}, //RESET port58
    [MODULE_LPMODE_1]    = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_L, 0x01 << 0, 1}, //LPMODE port1
    [MODULE_LPMODE_2]    = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_L, 0x01 << 1, 1}, //LPMODE port2
    [MODULE_LPMODE_9]    = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_L, 0x01 << 2, 1}, //LPMODE port9
    [MODULE_LPMODE_10]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_L, 0x01 << 3, 1}, //LPMODE port10
    [MODULE_LPMODE_17]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_L, 0x01 << 4, 1}, //LPMODE port17
    [MODULE_LPMODE_18]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_L, 0x01 << 5, 1}, //LPMODE port18
    [MODULE_LPMODE_25]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_L, 0x01 << 6, 1}, //LPMODE port25
    [MODULE_LPMODE_26]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_L, 0x01 << 7, 1}, //LPMODE port26
    [MODULE_LPMODE_33]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_L, 0x01 << 0, 1}, //LPMODE port33
    [MODULE_LPMODE_34]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_L, 0x01 << 1, 1}, //LPMODE port34
    [MODULE_LPMODE_41]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_L, 0x01 << 2, 1}, //LPMODE port41
    [MODULE_LPMODE_42]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_L, 0x01 << 3, 1}, //LPMODE port42
    [MODULE_LPMODE_49]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_L, 0x01 << 4, 1}, //LPMODE port49
    [MODULE_LPMODE_50]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_L, 0x01 << 5, 1}, //LPMODE port50
    [MODULE_LPMODE_57]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_L, 0x01 << 6, 1}, //LPMODE port57
    [MODULE_LPMODE_58]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_L, 0x01 << 7, 1}, //LPMODE port58

    /*MEZZ TOP R*/
    [MODULE_PRESENT_65]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_R, 0x01 << 0, 1}, //PRESENT port65
    [MODULE_PRESENT_66]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_R, 0x01 << 1, 1}, //PRESENT port66
    [MODULE_PRESENT_73]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_R, 0x01 << 2, 1}, //PRESENT port73
    [MODULE_PRESENT_74]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_R, 0x01 << 3, 1}, //PRESENT port74
    [MODULE_PRESENT_81]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_R, 0x01 << 4, 1}, //PRESENT port81
    [MODULE_PRESENT_82]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_R, 0x01 << 5, 1}, //PRESENT port82
    [MODULE_PRESENT_89]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_R, 0x01 << 6, 1}, //PRESENT port89
    [MODULE_PRESENT_90]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_TOP_R, 0x01 << 7, 1}, //PRESENT port90
    [MODULE_PRESENT_97]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_R, 0x01 << 0, 1}, //PRESENT port97
    [MODULE_PRESENT_98]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_R, 0x01 << 1, 1}, //PRESENT port98
    [MODULE_PRESENT_105] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_R, 0x01 << 2, 1}, //PRESENT port105
    [MODULE_PRESENT_106] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_R, 0x01 << 3, 1}, //PRESENT port106
    [MODULE_PRESENT_113] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_R, 0x01 << 4, 1}, //PRESENT port113
    [MODULE_PRESENT_114] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_R, 0x01 << 5, 1}, //PRESENT port114
    [MODULE_PRESENT_121] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_R, 0x01 << 6, 1}, //PRESENT port121
    [MODULE_PRESENT_122] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_TOP_R, 0x01 << 7, 1}, //PRESENT port122
    [MODULE_RESET_65]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_R, 0x01 << 0, 1}, //RESET port65
    [MODULE_RESET_66]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_R, 0x01 << 1, 1}, //RESET port66
    [MODULE_RESET_73]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_R, 0x01 << 2, 1}, //RESET port73
    [MODULE_RESET_74]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_R, 0x01 << 3, 1}, //RESET port74
    [MODULE_RESET_81]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_R, 0x01 << 4, 1}, //RESET port81
    [MODULE_RESET_82]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_R, 0x01 << 5, 1}, //RESET port82
    [MODULE_RESET_89]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_R, 0x01 << 6, 1}, //RESET port89
    [MODULE_RESET_90]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_TOP_R, 0x01 << 7, 1}, //RESET port90
    [MODULE_RESET_97]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_R, 0x01 << 0, 1}, //RESET port97
    [MODULE_RESET_98]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_R, 0x01 << 1, 1}, //RESET port98
    [MODULE_RESET_105]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_R, 0x01 << 2, 1}, //RESET port105
    [MODULE_RESET_106]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_R, 0x01 << 3, 1}, //RESET port106
    [MODULE_RESET_113]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_R, 0x01 << 4, 1}, //RESET port113
    [MODULE_RESET_114]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_R, 0x01 << 5, 1}, //RESET port114
    [MODULE_RESET_121]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_R, 0x01 << 6, 1}, //RESET port121
    [MODULE_RESET_122]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_TOP_R, 0x01 << 7, 1}, //RESET port122
    [MODULE_LPMODE_65]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_R, 0x01 << 0, 1}, //LPMODE port65
    [MODULE_LPMODE_66]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_R, 0x01 << 1, 1}, //LPMODE port66
    [MODULE_LPMODE_73]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_R, 0x01 << 2, 1}, //LPMODE port73
    [MODULE_LPMODE_74]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_R, 0x01 << 3, 1}, //LPMODE port74
    [MODULE_LPMODE_81]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_R, 0x01 << 4, 1}, //LPMODE port81
    [MODULE_LPMODE_82]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_R, 0x01 << 5, 1}, //LPMODE port82
    [MODULE_LPMODE_89]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_R, 0x01 << 6, 1}, //LPMODE port89
    [MODULE_LPMODE_90]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_TOP_R, 0x01 << 7, 1}, //LPMODE port90
    [MODULE_LPMODE_97]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_R, 0x01 << 0, 1}, //LPMODE port97
    [MODULE_LPMODE_98]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_R, 0x01 << 1, 1}, //LPMODE port98
    [MODULE_LPMODE_105]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_R, 0x01 << 2, 1}, //LPMODE port105
    [MODULE_LPMODE_106]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_R, 0x01 << 3, 1}, //LPMODE port106
    [MODULE_LPMODE_113]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_R, 0x01 << 4, 1}, //LPMODE port113
    [MODULE_LPMODE_114]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_R, 0x01 << 5, 1}, //LPMODE port114
    [MODULE_LPMODE_121]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_R, 0x01 << 6, 1}, //LPMODE port121
    [MODULE_LPMODE_122]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_TOP_R, 0x01 << 7, 1}, //LPMODE port122

    /*MEZZ BOT L*/
    [MODULE_PRESENT_7]   = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_L, 0x01 << 0, 1}, //PRESENT port7
    [MODULE_PRESENT_8]   = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_L, 0x01 << 1, 1}, //PRESENT port8
    [MODULE_PRESENT_15]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_L, 0x01 << 2, 1}, //PRESENT port15
    [MODULE_PRESENT_16]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_L, 0x01 << 3, 1}, //PRESENT port16
    [MODULE_PRESENT_23]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_L, 0x01 << 4, 1}, //PRESENT port23
    [MODULE_PRESENT_24]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_L, 0x01 << 5, 1}, //PRESENT port24
    [MODULE_PRESENT_31]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_L, 0x01 << 6, 1}, //PRESENT port31
    [MODULE_PRESENT_32]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_L, 0x01 << 7, 1}, //PRESENT port32
    [MODULE_PRESENT_39]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_L, 0x01 << 0, 1}, //PRESENT port39
    [MODULE_PRESENT_40]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_L, 0x01 << 1, 1}, //PRESENT port40
    [MODULE_PRESENT_47]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_L, 0x01 << 2, 1}, //PRESENT port47
    [MODULE_PRESENT_48]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_L, 0x01 << 3, 1}, //PRESENT port48
    [MODULE_PRESENT_55]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_L, 0x01 << 4, 1}, //PRESENT port55
    [MODULE_PRESENT_56]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_L, 0x01 << 5, 1}, //PRESENT port56
    [MODULE_PRESENT_63]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_L, 0x01 << 6, 1}, //PRESENT port63
    [MODULE_PRESENT_64]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_L, 0x01 << 7, 1}, //PRESENT port64
    [MODULE_RESET_7]     = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_L, 0x01 << 0, 1}, //RESET port7
    [MODULE_RESET_8]     = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_L, 0x01 << 1, 1}, //RESET port8
    [MODULE_RESET_15]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_L, 0x01 << 2, 1}, //RESET port15
    [MODULE_RESET_16]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_L, 0x01 << 3, 1}, //RESET port16
    [MODULE_RESET_23]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_L, 0x01 << 4, 1}, //RESET port23
    [MODULE_RESET_24]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_L, 0x01 << 5, 1}, //RESET port24
    [MODULE_RESET_31]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_L, 0x01 << 6, 1}, //RESET port31
    [MODULE_RESET_32]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_L, 0x01 << 7, 1}, //RESET port32
    [MODULE_RESET_39]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_L, 0x01 << 0, 1}, //RESET port39
    [MODULE_RESET_40]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_L, 0x01 << 1, 1}, //RESET port40
    [MODULE_RESET_47]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_L, 0x01 << 2, 1}, //RESET port47
    [MODULE_RESET_48]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_L, 0x01 << 3, 1}, //RESET port48
    [MODULE_RESET_55]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_L, 0x01 << 4, 1}, //RESET port55
    [MODULE_RESET_56]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_L, 0x01 << 5, 1}, //RESET port56
    [MODULE_RESET_63]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_L, 0x01 << 6, 1}, //RESET port63
    [MODULE_RESET_64]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_L, 0x01 << 7, 1}, //RESET port64
    [MODULE_LPMODE_7]    = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_L, 0x01 << 0, 1}, //LPMODE port7
    [MODULE_LPMODE_8]    = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_L, 0x01 << 1, 1}, //LPMODE port8
    [MODULE_LPMODE_15]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_L, 0x01 << 2, 1}, //LPMODE port15
    [MODULE_LPMODE_16]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_L, 0x01 << 3, 1}, //LPMODE port16
    [MODULE_LPMODE_23]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_L, 0x01 << 4, 1}, //LPMODE port23
    [MODULE_LPMODE_24]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_L, 0x01 << 5, 1}, //LPMODE port24
    [MODULE_LPMODE_31]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_L, 0x01 << 6, 1}, //LPMODE port31
    [MODULE_LPMODE_32]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_L, 0x01 << 7, 1}, //LPMODE port32
    [MODULE_LPMODE_39]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_L, 0x01 << 0, 1}, //LPMODE port39
    [MODULE_LPMODE_40]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_L, 0x01 << 1, 1}, //LPMODE port40
    [MODULE_LPMODE_47]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_L, 0x01 << 2, 1}, //LPMODE port47
    [MODULE_LPMODE_48]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_L, 0x01 << 3, 1}, //LPMODE port48
    [MODULE_LPMODE_55]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_L, 0x01 << 4, 1}, //LPMODE port55
    [MODULE_LPMODE_56]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_L, 0x01 << 5, 1}, //LPMODE port56
    [MODULE_LPMODE_63]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_L, 0x01 << 6, 1}, //LPMODE port63
    [MODULE_LPMODE_64]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_L, 0x01 << 7, 1}, //LPMODE port64

    /*MEZZ BOT R*/
    [MODULE_PRESENT_71]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_R, 0x01 << 0, 1}, //PRESENT port71
    [MODULE_PRESENT_72]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_R, 0x01 << 1, 1}, //PRESENT port72
    [MODULE_PRESENT_79]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_R, 0x01 << 2, 1}, //PRESENT port79
    [MODULE_PRESENT_80]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_R, 0x01 << 3, 1}, //PRESENT port80
    [MODULE_PRESENT_87]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_R, 0x01 << 4, 1}, //PRESENT port87
    [MODULE_PRESENT_88]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_R, 0x01 << 5, 1}, //PRESENT port88
    [MODULE_PRESENT_95]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_R, 0x01 << 6, 1}, //PRESENT port95
    [MODULE_PRESENT_96]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MEZZ_BOT_R, 0x01 << 7, 1}, //PRESENT port96
    [MODULE_PRESENT_103] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_R, 0x01 << 0, 1}, //PRESENT port103
    [MODULE_PRESENT_104] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_R, 0x01 << 1, 1}, //PRESENT port104
    [MODULE_PRESENT_111] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_R, 0x01 << 2, 1}, //PRESENT port111
    [MODULE_PRESENT_112] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_R, 0x01 << 3, 1}, //PRESENT port112
    [MODULE_PRESENT_119] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_R, 0x01 << 4, 1}, //PRESENT port119
    [MODULE_PRESENT_120] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_R, 0x01 << 5, 1}, //PRESENT port120
    [MODULE_PRESENT_127] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_R, 0x01 << 6, 1}, //PRESENT port127
    [MODULE_PRESENT_128] = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MEZZ_BOT_R, 0x01 << 7, 1}, //PRESENT port128
    [MODULE_RESET_71]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_R, 0x01 << 0, 1}, //RESET port71
    [MODULE_RESET_72]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_R, 0x01 << 1, 1}, //RESET port72
    [MODULE_RESET_79]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_R, 0x01 << 2, 1}, //RESET port79
    [MODULE_RESET_80]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_R, 0x01 << 3, 1}, //RESET port80
    [MODULE_RESET_87]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_R, 0x01 << 4, 1}, //RESET port87
    [MODULE_RESET_88]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_R, 0x01 << 5, 1}, //RESET port88
    [MODULE_RESET_95]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_R, 0x01 << 6, 1}, //RESET port95
    [MODULE_RESET_96]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MEZZ_BOT_R, 0x01 << 7, 1}, //RESET port96
    [MODULE_RESET_103]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_R, 0x01 << 0, 1}, //RESET port103
    [MODULE_RESET_104]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_R, 0x01 << 1, 1}, //RESET port104
    [MODULE_RESET_111]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_R, 0x01 << 2, 1}, //RESET port111
    [MODULE_RESET_112]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_R, 0x01 << 3, 1}, //RESET port112
    [MODULE_RESET_119]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_R, 0x01 << 4, 1}, //RESET port119
    [MODULE_RESET_120]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_R, 0x01 << 5, 1}, //RESET port120
    [MODULE_RESET_127]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_R, 0x01 << 6, 1}, //RESET port127
    [MODULE_RESET_128]   = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MEZZ_BOT_R, 0x01 << 7, 1}, //RESET port128
    [MODULE_LPMODE_71]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_R, 0x01 << 0, 1}, //LPMODE port71
    [MODULE_LPMODE_72]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_R, 0x01 << 1, 1}, //LPMODE port71
    [MODULE_LPMODE_79]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_R, 0x01 << 2, 1}, //LPMODE port79
    [MODULE_LPMODE_80]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_R, 0x01 << 3, 1}, //LPMODE port80
    [MODULE_LPMODE_87]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_R, 0x01 << 4, 1}, //LPMODE port87
    [MODULE_LPMODE_88]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_R, 0x01 << 5, 1}, //LPMODE port88
    [MODULE_LPMODE_95]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_R, 0x01 << 6, 1}, //LPMODE port95
    [MODULE_LPMODE_96]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MEZZ_BOT_R, 0x01 << 7, 1}, //LPMODE port96
    [MODULE_LPMODE_103]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_R, 0x01 << 0, 1}, //LPMODE port103
    [MODULE_LPMODE_104]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_R, 0x01 << 1, 1}, //LPMODE port104
    [MODULE_LPMODE_111]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_R, 0x01 << 2, 1}, //LPMODE port111
    [MODULE_LPMODE_112]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_R, 0x01 << 3, 1}, //LPMODE port112
    [MODULE_LPMODE_119]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_R, 0x01 << 4, 1}, //LPMODE port119
    [MODULE_LPMODE_120]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_R, 0x01 << 5, 1}, //LPMODE port120
    [MODULE_LPMODE_127]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_R, 0x01 << 6, 1}, //LPMODE port127
    [MODULE_LPMODE_128]  = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MEZZ_BOT_R, 0x01 << 7, 1}, //LPMODE port128

    /*PORT 0*/
    [MODULE_PRESENT_3]   = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //PRESENT port3
    [MODULE_PRESENT_4]   = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //PRESENT port4
    [MODULE_PRESENT_5]   = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //PRESENT port5
    [MODULE_PRESENT_6]   = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //PRESENT port6
    [MODULE_PRESENT_11]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //PRESENT port11
    [MODULE_PRESENT_12]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //PRESENT port12
    [MODULE_PRESENT_13]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //PRESENT port13
    [MODULE_PRESENT_14]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //PRESENT port14
    [MODULE_PRESENT_19]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //PRESENT port19
    [MODULE_PRESENT_20]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //PRESENT port20
    [MODULE_PRESENT_21]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //PRESENT port21
    [MODULE_PRESENT_22]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //PRESENT port22
    [MODULE_PRESENT_27]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //PRESENT port27
    [MODULE_PRESENT_28]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //PRESENT port28
    [MODULE_PRESENT_29]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //PRESENT port29
    [MODULE_PRESENT_30]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //PRESENT port30
    [MODULE_PRESENT_35]  = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //PRESENT port35
    [MODULE_PRESENT_36]  = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //PRESENT port36
    [MODULE_PRESENT_37]  = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //PRESENT port37
    [MODULE_PRESENT_38]  = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //PRESENT port38
    [MODULE_PRESENT_43]  = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //PRESENT port43
    [MODULE_PRESENT_44]  = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //PRESENT port44
    [MODULE_PRESENT_45]  = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //PRESENT port45
    [MODULE_PRESENT_46]  = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //PRESENT port46
    [MODULE_PRESENT_51]  = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //PRESENT port51
    [MODULE_PRESENT_52]  = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //PRESENT port52
    [MODULE_PRESENT_53]  = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //PRESENT port53
    [MODULE_PRESENT_54]  = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //PRESENT port54
    [MODULE_PRESENT_59]  = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //PRESENT port59
    [MODULE_PRESENT_60]  = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //PRESENT port60
    [MODULE_PRESENT_61]  = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //PRESENT port61
    [MODULE_PRESENT_62]  = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //PRESENT port62
    [MODULE_RESET_3]     = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //RESET port3
    [MODULE_RESET_4]     = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //RESET port4
    [MODULE_RESET_5]     = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //RESET port5
    [MODULE_RESET_6]     = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //RESET port6
    [MODULE_RESET_11]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //RESET port11
    [MODULE_RESET_12]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //RESET port12
    [MODULE_RESET_13]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //RESET port13
    [MODULE_RESET_14]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //RESET port14
    [MODULE_RESET_19]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //RESET port19
    [MODULE_RESET_20]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //RESET port20
    [MODULE_RESET_21]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //RESET port21
    [MODULE_RESET_22]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //RESET port22
    [MODULE_RESET_27]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //RESET port27
    [MODULE_RESET_28]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //RESET port28
    [MODULE_RESET_29]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //RESET port29
    [MODULE_RESET_30]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //RESET port30
    [MODULE_RESET_35]    = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //RESET port35
    [MODULE_RESET_36]    = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //RESET port36
    [MODULE_RESET_37]    = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //RESET port37
    [MODULE_RESET_38]    = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //RESET port38
    [MODULE_RESET_43]    = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //RESET port43
    [MODULE_RESET_44]    = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //RESET port44
    [MODULE_RESET_45]    = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //RESET port45
    [MODULE_RESET_46]    = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //RESET port46
    [MODULE_RESET_51]    = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //RESET port51
    [MODULE_RESET_52]    = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //RESET port52
    [MODULE_RESET_53]    = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //RESET port53
    [MODULE_RESET_54]    = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //RESET port54
    [MODULE_RESET_59]    = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //RESET port59
    [MODULE_RESET_60]    = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //RESET port60
    [MODULE_RESET_61]    = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //RESET port61
    [MODULE_RESET_62]    = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //RESET port62
    [MODULE_LPMODE_3]    = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //LPMODE port3
    [MODULE_LPMODE_4]    = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //LPMODE port4
    [MODULE_LPMODE_5]    = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //LPMODE port5
    [MODULE_LPMODE_6]    = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //LPMODE port6
    [MODULE_LPMODE_11]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //LPMODE port11
    [MODULE_LPMODE_12]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //LPMODE port12
    [MODULE_LPMODE_13]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //LPMODE port13
    [MODULE_LPMODE_14]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //LPMODE port14
    [MODULE_LPMODE_19]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //LPMODE port19
    [MODULE_LPMODE_20]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //LPMODE port20
    [MODULE_LPMODE_21]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //LPMODE port21
    [MODULE_LPMODE_22]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //LPMODE port22
    [MODULE_LPMODE_27]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //LPMODE port27
    [MODULE_LPMODE_28]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //LPMODE port28
    [MODULE_LPMODE_29]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //LPMODE port29
    [MODULE_LPMODE_30]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //LPMODE port30
    [MODULE_LPMODE_35]   = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //LPMODE port35
    [MODULE_LPMODE_36]   = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //LPMODE port36
    [MODULE_LPMODE_37]   = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //LPMODE port37
    [MODULE_LPMODE_38]   = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //LPMODE port38
    [MODULE_LPMODE_43]   = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //LPMODE port43
    [MODULE_LPMODE_44]   = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //LPMODE port44
    [MODULE_LPMODE_45]   = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //LPMODE port45
    [MODULE_LPMODE_46]   = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //LPMODE port46
    [MODULE_LPMODE_51]   = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD0, 0x01 << 0, 1}, //LPMODE port51
    [MODULE_LPMODE_52]   = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD0, 0x01 << 1, 1}, //LPMODE port52
    [MODULE_LPMODE_53]   = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD0, 0x01 << 2, 1}, //LPMODE port53
    [MODULE_LPMODE_54]   = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD0, 0x01 << 3, 1}, //LPMODE port54
    [MODULE_LPMODE_59]   = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD0, 0x01 << 4, 1}, //LPMODE port59
    [MODULE_LPMODE_60]   = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD0, 0x01 << 5, 1}, //LPMODE port60
    [MODULE_LPMODE_61]   = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD0, 0x01 << 6, 1}, //LPMODE port61
    [MODULE_LPMODE_62]   = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD0, 0x01 << 7, 1}, //LPMODE port62

    /*PORT 1*/
    [MODULE_PRESENT_67]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //PRESENT port67
    [MODULE_PRESENT_68]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //PRESENT port68
    [MODULE_PRESENT_69]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //PRESENT port69
    [MODULE_PRESENT_70]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //PRESENT port70
    [MODULE_PRESENT_75]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //PRESENT port75
    [MODULE_PRESENT_76]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //PRESENT port76
    [MODULE_PRESENT_77]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //PRESENT port77
    [MODULE_PRESENT_78]  = {CPLD_PCIE_START_OFFSET + 0x88, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //PRESENT port78
    [MODULE_PRESENT_83]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //PRESENT port83
    [MODULE_PRESENT_84]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //PRESENT port84
    [MODULE_PRESENT_85]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //PRESENT port85
    [MODULE_PRESENT_86]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //PRESENT port86
    [MODULE_PRESENT_91]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //PRESENT port91
    [MODULE_PRESENT_92]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //PRESENT port92
    [MODULE_PRESENT_93]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //PRESENT port93
    [MODULE_PRESENT_94]  = {CPLD_PCIE_START_OFFSET + 0x89, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //PRESENT port94
    [MODULE_PRESENT_99]  = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //PRESENT port99
    [MODULE_PRESENT_100] = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //PRESENT port100
    [MODULE_PRESENT_101] = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //PRESENT port101
    [MODULE_PRESENT_102] = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //PRESENT port102
    [MODULE_PRESENT_107] = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //PRESENT port107
    [MODULE_PRESENT_108] = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //PRESENT port108
    [MODULE_PRESENT_109] = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //PRESENT port109
    [MODULE_PRESENT_110] = {CPLD_PCIE_START_OFFSET + 0x8A, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //PRESENT port110
    [MODULE_PRESENT_115] = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //PRESENT port115
    [MODULE_PRESENT_116] = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //PRESENT port116
    [MODULE_PRESENT_117] = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //PRESENT port117
    [MODULE_PRESENT_118] = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //PRESENT port118
    [MODULE_PRESENT_123] = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //PRESENT port123
    [MODULE_PRESENT_124] = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //PRESENT port124
    [MODULE_PRESENT_125] = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //PRESENT port125
    [MODULE_PRESENT_126] = {CPLD_PCIE_START_OFFSET + 0x8B, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //PRESENT port126
    [MODULE_RESET_67]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //RESET port67
    [MODULE_RESET_68]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //RESET port68
    [MODULE_RESET_69]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //RESET port69
    [MODULE_RESET_70]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //RESET port70
    [MODULE_RESET_75]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //RESET port75
    [MODULE_RESET_76]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //RESET port76
    [MODULE_RESET_77]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //RESET port77
    [MODULE_RESET_78]    = {CPLD_PCIE_START_OFFSET + 0x78, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //RESET port78
    [MODULE_RESET_83]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //RESET port83
    [MODULE_RESET_84]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //RESET port84
    [MODULE_RESET_85]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //RESET port85
    [MODULE_RESET_86]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //RESET port86
    [MODULE_RESET_91]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //RESET port91
    [MODULE_RESET_92]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //RESET port92
    [MODULE_RESET_93]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //RESET port93
    [MODULE_RESET_94]    = {CPLD_PCIE_START_OFFSET + 0x79, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //RESET port94
    [MODULE_RESET_99]    = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //RESET port99
    [MODULE_RESET_100]   = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //RESET port100
    [MODULE_RESET_101]   = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //RESET port101
    [MODULE_RESET_102]   = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //RESET port102
    [MODULE_RESET_107]   = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //RESET port107
    [MODULE_RESET_108]   = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //RESET port108
    [MODULE_RESET_109]   = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //RESET port109
    [MODULE_RESET_110]   = {CPLD_PCIE_START_OFFSET + 0x7A, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //RESET port110
    [MODULE_RESET_115]   = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //RESET port115
    [MODULE_RESET_116]   = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //RESET port116
    [MODULE_RESET_117]   = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //RESET port117
    [MODULE_RESET_118]   = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //RESET port118
    [MODULE_RESET_123]   = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //RESET port123
    [MODULE_RESET_124]   = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //RESET port124
    [MODULE_RESET_125]   = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //RESET port125
    [MODULE_RESET_126]   = {CPLD_PCIE_START_OFFSET + 0x7B, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //RESET port126
    [MODULE_LPMODE_67]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //LPMODE port67
    [MODULE_LPMODE_68]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //LPMODE port68
    [MODULE_LPMODE_69]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //LPMODE port69
    [MODULE_LPMODE_70]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //LPMODE port70
    [MODULE_LPMODE_75]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //LPMODE port75
    [MODULE_LPMODE_76]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //LPMODE port76
    [MODULE_LPMODE_77]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //LPMODE port77
    [MODULE_LPMODE_78]   = {CPLD_PCIE_START_OFFSET + 0x70, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //LPMODE port78
    [MODULE_LPMODE_83]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //LPMODE port83
    [MODULE_LPMODE_84]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //LPMODE port84
    [MODULE_LPMODE_85]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //LPMODE port85
    [MODULE_LPMODE_86]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //LPMODE port86
    [MODULE_LPMODE_91]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //LPMODE port91
    [MODULE_LPMODE_92]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //LPMODE port92
    [MODULE_LPMODE_93]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //LPMODE port93
    [MODULE_LPMODE_94]   = {CPLD_PCIE_START_OFFSET + 0x71, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //LPMODE port94
    [MODULE_LPMODE_99]   = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //LPMODE port99
    [MODULE_LPMODE_100]  = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //LPMODE port100
    [MODULE_LPMODE_101]  = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //LPMODE port101
    [MODULE_LPMODE_102]  = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //LPMODE port102
    [MODULE_LPMODE_107]  = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //LPMODE port107
    [MODULE_LPMODE_108]  = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //LPMODE port108
    [MODULE_LPMODE_109]  = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //LPMODE port109
    [MODULE_LPMODE_110]  = {CPLD_PCIE_START_OFFSET + 0x72, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //LPMODE port110
    [MODULE_LPMODE_115]  = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //LPMODE port115
    [MODULE_LPMODE_116]  = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //LPMODE port116
    [MODULE_LPMODE_117]  = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD1, 0x01 << 2, 1}, //LPMODE port117
    [MODULE_LPMODE_118]  = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD1, 0x01 << 3, 1}, //LPMODE port118
    [MODULE_LPMODE_123]  = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD1, 0x01 << 4, 1}, //LPMODE port123
    [MODULE_LPMODE_124]  = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD1, 0x01 << 5, 1}, //LPMODE port124
    [MODULE_LPMODE_125]  = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD1, 0x01 << 6, 1}, //LPMODE port125
    [MODULE_LPMODE_126]  = {CPLD_PCIE_START_OFFSET + 0x73, SPI_MUX_MB_CPLD1, 0x01 << 7, 1}, //LPMODE port126

    [MODULE_TX_DISABLE_129] = {CPLD_PCIE_START_OFFSET + 0x18, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //TX_DISABLE port129
    [MODULE_TX_DISABLE_130] = {CPLD_PCIE_START_OFFSET + 0x18, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //TX_DISABLE port130
    [MODULE_TX_FAULT_129]   = {CPLD_PCIE_START_OFFSET + 0x10, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //TX_FAULT port129
    [MODULE_TX_FAULT_130]   = {CPLD_PCIE_START_OFFSET + 0x10, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //TX_FAULT port130
    [MODULE_RX_LOS_129]     = {CPLD_PCIE_START_OFFSET + 0x20, SPI_MUX_MB_CPLD1, 0x01 << 0, 1}, //RX_LOS port129
    [MODULE_RX_LOS_130]     = {CPLD_PCIE_START_OFFSET + 0x20, SPI_MUX_MB_CPLD1, 0x01 << 1, 1}, //RX_LOS port130
};

static inline unsigned int fpga_read(const void __iomem *addr, u32 spi_mask)
{
    wait_spi(spi_mask, usecs_to_jiffies(20));
    return ioread8(addr);
}

static inline void fpga_write(void __iomem *addr, u8 val, u32 spi_mask)
{
    wait_spi(spi_mask, usecs_to_jiffies(20));
    iowrite8(val, addr);
}

static ssize_t status_read(struct device *dev, struct device_attribute *da, char *buf)
{
    struct sensor_device_attribute *attr = to_sensor_dev_attr(da);
    struct as1813_128o_fpga_data *fpga_ctl = dev_get_drvdata(dev);
    ssize_t ret = -EINVAL;
    u16 reg;
    u8 fpga_spi_mux_data, reg_val;


    reg = attribute_mappings[attr->index].reg;
    fpga_spi_mux_data = attribute_mappings[attr->index].spi_mux;

    LOCK(&cpld_access_lock);
    iowrite8(fpga_spi_mux_data, spi_mux_reg);
    reg_val = fpga_read(fpga_ctl->pci_fpga_dev.data_base_addr0 + reg, SPI_BUSY_MASK_CPLD);
    UNLOCK(&cpld_access_lock);
    reg_val = !!(reg_val & attribute_mappings[attr->index].mask);

    if (attribute_mappings[attr->index].revert) 
        reg_val = !reg_val;
    ret = sprintf(buf, "%u\n", reg_val);

    return ret;
}

static ssize_t status_write(struct device *dev, struct device_attribute *da,
                            const char *buf, size_t count)
{
    struct sensor_device_attribute *attr = to_sensor_dev_attr(da);
    struct as1813_128o_fpga_data *fpga_ctl = dev_get_drvdata(dev);
    void __iomem *addr;
    int status;
    u16 reg;
    u8 input;
    u8 reg_val, bit_mask, should_set_bit;

    status = kstrtou8(buf, 10, &input);
    if (status) {
        return status;
    }

    reg = attribute_mappings[attr->index].reg;
    bit_mask = attribute_mappings[attr->index].mask;
    addr = fpga_ctl->pci_fpga_dev.data_base_addr0;
    should_set_bit = attribute_mappings[attr->index].revert ? !input : input;

    LOCK(&cpld_access_lock);
    iowrite8(attribute_mappings[attr->index].spi_mux, spi_mux_reg);
    reg_val = fpga_read(addr + reg, SPI_BUSY_MASK_CPLD);
    if (should_set_bit) {
        reg_val |= bit_mask;
    } else {
        reg_val &= ~bit_mask;
    }
    fpga_write(addr + reg, reg_val, SPI_BUSY_MASK_CPLD);
    UNLOCK(&cpld_access_lock);

    return count;
}

struct _port_data {
    u16 offset;
    u16 spi_mux;
};
/* ============PCIe Bar Offset to I2C Master Mapping============== */
static const struct _port_data port[PORT_NUM]= {
    /* MEZZ_TOP_L */
    {0x2100, SPI_MUX_MEZZ_TOP_L},/* 0x2100 - 0x2110  I2C Master OSFP port1 */
    {0x2120, SPI_MUX_MEZZ_TOP_L},/* 0x2120 - 0x2130  I2C Master OSFP port2 */

    /* MB_CPLD0 */
    {0x2100, SPI_MUX_MB_CPLD0},/* 0x2100 - 0x2110  I2C Master OSFP port3 */
    {0x2120, SPI_MUX_MB_CPLD0},/* 0x2120 - 0x2130  I2C Master OSFP port4 */
    {0x2140, SPI_MUX_MB_CPLD0},/* 0x2140 - 0x2150  I2C Master OSFP port5 */
    {0x2160, SPI_MUX_MB_CPLD0},/* 0x2160 - 0x2170  I2C Master OSFP port6 */

    /* MEZZ_BOT_L */
    {0x2100, SPI_MUX_MEZZ_BOT_L},/* 0x2100 - 0x2110  I2C Master OSFP port7 */
    {0x2120, SPI_MUX_MEZZ_BOT_L},/* 0x2120 - 0x2130  I2C Master OSFP port8 */

    /* MEZZ_TOP_L */
    {0x2140, SPI_MUX_MEZZ_TOP_L},/* 0x2140 - 0x2150  I2C Master OSFP port9 */
    {0x2160, SPI_MUX_MEZZ_TOP_L},/* 0x2160 - 0x2170  I2C Master OSFP port10 */

    /* MB_CPLD0 */
    {0x2180, SPI_MUX_MB_CPLD0},/* 0x2180 - 0x2190  I2C Master OSFP port11 */
    {0x21A0, SPI_MUX_MB_CPLD0},/* 0x21A0 - 0x21B0  I2C Master OSFP port12 */
    {0x21C0, SPI_MUX_MB_CPLD0},/* 0x21C0 - 0x21D0  I2C Master OSFP port13 */
    {0x21E0, SPI_MUX_MB_CPLD0},/* 0x21E0 - 0x21F0  I2C Master OSFP port14 */

    /* MEZZ_BOT_L */
    {0x2140, SPI_MUX_MEZZ_BOT_L},/* 0x2140 - 0x2150  I2C Master OSFP port15 */
    {0x2160, SPI_MUX_MEZZ_BOT_L},/* 0x2160 - 0x2170  I2C Master OSFP port16 */

    /* MEZZ_TOP_L */
    {0x2180, SPI_MUX_MEZZ_TOP_L},/* 0x2180 - 0x2190  I2C Master OSFP port17 */
    {0x21A0, SPI_MUX_MEZZ_TOP_L},/* 0x21A0 - 0x21B0  I2C Master OSFP port18 */

    /* MB_CPLD0 */
    {0x2200, SPI_MUX_MB_CPLD0},/* 0x2200 - 0x2210  I2C Master OSFP port19 */
    {0x2220, SPI_MUX_MB_CPLD0},/* 0x2220 - 0x2230  I2C Master OSFP port20 */
    {0x2240, SPI_MUX_MB_CPLD0},/* 0x2240 - 0x2250  I2C Master OSFP port21 */
    {0x2260, SPI_MUX_MB_CPLD0},/* 0x2260 - 0x2270  I2C Master OSFP port22 */

    /* MEZZ_BOT_L */
    {0x2180, SPI_MUX_MEZZ_BOT_L},/* 0x2180 - 0x2190  I2C Master OSFP port23 */
    {0x21A0, SPI_MUX_MEZZ_BOT_L},/* 0x21A0 - 0x21B0  I2C Master OSFP port24 */

    /* MEZZ_TOP_L */
    {0x21C0, SPI_MUX_MEZZ_TOP_L},/* 0x21C0 - 0x21D0  I2C Master OSFP port25 */
    {0x21E0, SPI_MUX_MEZZ_TOP_L},/* 0x21E0 - 0x21F0  I2C Master OSFP port26 */

    /* MB_CPLD0 */
    {0x2280, SPI_MUX_MB_CPLD0},/* 0x2280 - 0x2290  I2C Master OSFP port27 */
    {0x22A0, SPI_MUX_MB_CPLD0},/* 0x22A0 - 0x22B0  I2C Master OSFP port28 */
    {0x22C0, SPI_MUX_MB_CPLD0},/* 0x22C0 - 0x22D0  I2C Master OSFP port29 */
    {0x22E0, SPI_MUX_MB_CPLD0},/* 0x22E0 - 0x22F0  I2C Master OSFP port30 */

    /* MEZZ_BOT_L */
    {0x21C0, SPI_MUX_MEZZ_BOT_L},/* 0x21C0 - 0x21D0  I2C Master OSFP port31 */
    {0x21E0, SPI_MUX_MEZZ_BOT_L},/* 0x21E0 - 0x21F0  I2C Master OSFP port32 */

    /* MEZZ_TOP_L */
    {0x2200, SPI_MUX_MEZZ_TOP_L},/* 0x2200 - 0x2210  I2C Master OSFP port33 */
    {0x2220, SPI_MUX_MEZZ_TOP_L},/* 0x2220 - 0x2230  I2C Master OSFP port34 */

    /* MB_CPLD0 */
    {0x2300, SPI_MUX_MB_CPLD0},/* 0x2300 - 0x2310  I2C Master OSFP port35 */
    {0x2320, SPI_MUX_MB_CPLD0},/* 0x2320 - 0x2330  I2C Master OSFP port36 */
    {0x2340, SPI_MUX_MB_CPLD0},/* 0x2340 - 0x2350  I2C Master OSFP port37 */
    {0x2360, SPI_MUX_MB_CPLD0},/* 0x2360 - 0x2370  I2C Master OSFP port38 */

    /* MEZZ_BOT_L */
    {0x2200, SPI_MUX_MEZZ_BOT_L},/* 0x2200 - 0x2210  I2C Master OSFP port39 */
    {0x2220, SPI_MUX_MEZZ_BOT_L},/* 0x2220 - 0x2230  I2C Master OSFP port40 */

    /* MEZZ_TOP_L */
    {0x2240, SPI_MUX_MEZZ_TOP_L},/* 0x2240 - 0x2250  I2C Master OSFP port41 */
    {0x2260, SPI_MUX_MEZZ_TOP_L},/* 0x2260 - 0x2270  I2C Master OSFP port42 */

    /* MB_CPLD0 */
    {0x2380, SPI_MUX_MB_CPLD0},/* 0x2380 - 0x2390  I2C Master OSFP port43 */
    {0x23A0, SPI_MUX_MB_CPLD0},/* 0x23A0 - 0x23B0  I2C Master OSFP port44 */
    {0x23C0, SPI_MUX_MB_CPLD0},/* 0x23C0 - 0x23D0  I2C Master OSFP port45 */
    {0x23E0, SPI_MUX_MB_CPLD0},/* 0x23E0 - 0x23F0  I2C Master OSFP port46 */

    /* MEZZ_BOT_L */
    {0x2240, SPI_MUX_MEZZ_BOT_L},/* 0x2240 - 0x2250  I2C Master OSFP port47 */
    {0x2260, SPI_MUX_MEZZ_BOT_L},/* 0x2260 - 0x2270  I2C Master OSFP port48 */

    /* MEZZ_TOP_L */
    {0x2280, SPI_MUX_MEZZ_TOP_L},/* 0x2280 - 0x2290  I2C Master OSFP port49 */
    {0x22A0, SPI_MUX_MEZZ_TOP_L},/* 0x22A0 - 0x22B0  I2C Master OSFP port50 */

    /* MB_CPLD0 */
    {0x2400, SPI_MUX_MB_CPLD0},/* 0x2400 - 0x2410  I2C Master OSFP port51 */
    {0x2420, SPI_MUX_MB_CPLD0},/* 0x2420 - 0x2430  I2C Master OSFP port52 */
    {0x2440, SPI_MUX_MB_CPLD0},/* 0x2440 - 0x2450  I2C Master OSFP port53 */
    {0x2460, SPI_MUX_MB_CPLD0},/* 0x2460 - 0x2470  I2C Master OSFP port54 */

    /* MEZZ_BOT_L */
    {0x2280, SPI_MUX_MEZZ_BOT_L},/* 0x2280 - 0x2290  I2C Master OSFP port55 */
    {0x22A0, SPI_MUX_MEZZ_BOT_L},/* 0x22A0 - 0x22B0  I2C Master OSFP port56 */

    /* MEZZ_TOP_L */
    {0x22C0, SPI_MUX_MEZZ_TOP_L},/* 0x22C0 - 0x22D0  I2C Master OSFP port57 */
    {0x22E0, SPI_MUX_MEZZ_TOP_L},/* 0x22E0 - 0x22F0  I2C Master OSFP port58 */

    /* MB_CPLD0 */
    {0x2480, SPI_MUX_MB_CPLD0},/* 0x2480 - 0x2490  I2C Master OSFP port59 */
    {0x24A0, SPI_MUX_MB_CPLD0},/* 0x24A0 - 0x24B0  I2C Master OSFP port60 */
    {0x24C0, SPI_MUX_MB_CPLD0},/* 0x24C0 - 0x24D0  I2C Master OSFP port61 */
    {0x24E0, SPI_MUX_MB_CPLD0},/* 0x24E0 - 0x24F0  I2C Master OSFP port62 */

    /* MEZZ_BOT_L */
    {0x22C0, SPI_MUX_MEZZ_BOT_L},/* 0x22C0 - 0x22D0  I2C Master OSFP port63 */
    {0x22E0, SPI_MUX_MEZZ_BOT_L},/* 0x22E0 - 0x22F0  I2C Master OSFP port64 */

    /* MEZZ_TOP_R */
    {0x2100, SPI_MUX_MEZZ_TOP_R},/* 0x2100 - 0x2110  I2C Master OSFP port65 */
    {0x2120, SPI_MUX_MEZZ_TOP_R},/* 0x2120 - 0x2130  I2C Master OSFP port66 */

    /* MB_CPLD1 */
    {0x2100, SPI_MUX_MB_CPLD1},/* 0x2100 - 0x2110  I2C Master OSFP port67 */
    {0x2120, SPI_MUX_MB_CPLD1},/* 0x2120 - 0x2130  I2C Master OSFP port68 */
    {0x2140, SPI_MUX_MB_CPLD1},/* 0x2140 - 0x2150  I2C Master OSFP port69 */
    {0x2160, SPI_MUX_MB_CPLD1},/* 0x2160 - 0x2170  I2C Master OSFP port70 */

    /* MEZZ_BOT_R */
    {0x2100, SPI_MUX_MEZZ_BOT_R},/* 0x2100 - 0x2110  I2C Master OSFP port71 */
    {0x2120, SPI_MUX_MEZZ_BOT_R},/* 0x2120 - 0x2130  I2C Master OSFP port72 */

    /* MEZZ_TOP_R */
    {0x2140, SPI_MUX_MEZZ_TOP_R},/* 0x2140 - 0x2150  I2C Master OSFP port73 */
    {0x2160, SPI_MUX_MEZZ_TOP_R},/* 0x2160 - 0x2170  I2C Master OSFP port74 */

    /* MB_CPLD1 */
    {0x2180, SPI_MUX_MB_CPLD1},/* 0x2180 - 0x2190  I2C Master OSFP port75 */
    {0x21A0, SPI_MUX_MB_CPLD1},/* 0x21A0 - 0x21B0  I2C Master OSFP port76 */
    {0x21C0, SPI_MUX_MB_CPLD1},/* 0x21C0 - 0x21D0  I2C Master OSFP port77 */
    {0x21E0, SPI_MUX_MB_CPLD1},/* 0x21E0 - 0x21F0  I2C Master OSFP port78 */

    /* MEZZ_BOT_R */
    {0x2140, SPI_MUX_MEZZ_BOT_R},/* 0x2140 - 0x2150  I2C Master OSFP port79 */
    {0x2160, SPI_MUX_MEZZ_BOT_R},/* 0x2160 - 0x2170  I2C Master OSFP port80 */

    /* MEZZ_TOP_R */
    {0x2180, SPI_MUX_MEZZ_TOP_R},/* 0x2180 - 0x2190  I2C Master OSFP port81 */
    {0x21A0, SPI_MUX_MEZZ_TOP_R},/* 0x21A0 - 0x21B0  I2C Master OSFP port82 */

    /* MB_CPLD1 */
    {0x2200, SPI_MUX_MB_CPLD1},/* 0x2200 - 0x2210  I2C Master OSFP port83 */
    {0x2220, SPI_MUX_MB_CPLD1},/* 0x2220 - 0x2230  I2C Master OSFP port84 */
    {0x2240, SPI_MUX_MB_CPLD1},/* 0x2240 - 0x2250  I2C Master OSFP port85 */
    {0x2260, SPI_MUX_MB_CPLD1},/* 0x2260 - 0x2270  I2C Master OSFP port86 */

    /* MEZZ_BOT_R */
    {0x2180, SPI_MUX_MEZZ_BOT_R},/* 0x2180 - 0x2190  I2C Master OSFP port87 */
    {0x21A0, SPI_MUX_MEZZ_BOT_R},/* 0x21A0 - 0x21B0  I2C Master OSFP port88 */

    /* MEZZ_TOP_R */
    {0x21C0, SPI_MUX_MEZZ_TOP_R},/* 0x21C0 - 0x21D0  I2C Master OSFP port89 */
    {0x21E0, SPI_MUX_MEZZ_TOP_R},/* 0x21E0 - 0x21F0  I2C Master OSFP port90 */

    /* MB_CPLD1 */
    {0x2280, SPI_MUX_MB_CPLD1},/* 0x2280 - 0x2290  I2C Master OSFP port91 */
    {0x22A0, SPI_MUX_MB_CPLD1},/* 0x22A0 - 0x22B0  I2C Master OSFP port92 */
    {0x22C0, SPI_MUX_MB_CPLD1},/* 0x22C0 - 0x22D0  I2C Master OSFP port93 */
    {0x22E0, SPI_MUX_MB_CPLD1},/* 0x22E0 - 0x22F0  I2C Master OSFP port94 */

    /* MEZZ_BOT_R */
    {0x21C0, SPI_MUX_MEZZ_BOT_R},/* 0x21C0 - 0x21D0  I2C Master OSFP port95 */
    {0x21E0, SPI_MUX_MEZZ_BOT_R},/* 0x21E0 - 0x21F0  I2C Master OSFP port96 */

    /* MEZZ_TOP_R */
    {0x2200, SPI_MUX_MEZZ_TOP_R},/* 0x2200 - 0x2210  I2C Master OSFP port97 */
    {0x2220, SPI_MUX_MEZZ_TOP_R},/* 0x2220 - 0x2230  I2C Master OSFP port98 */

    /* MB_CPLD1 */
    {0x2300, SPI_MUX_MB_CPLD1},/* 0x2300 - 0x2310  I2C Master OSFP port99 */
    {0x2320, SPI_MUX_MB_CPLD1},/* 0x2320 - 0x2330  I2C Master OSFP port100 */
    {0x2340, SPI_MUX_MB_CPLD1},/* 0x2340 - 0x2350  I2C Master OSFP port101 */
    {0x2360, SPI_MUX_MB_CPLD1},/* 0x2360 - 0x2370  I2C Master OSFP port102 */

    /* MEZZ_BOT_R */
    {0x2200, SPI_MUX_MEZZ_BOT_R},/* 0x2200 - 0x2210  I2C Master OSFP port103 */
    {0x2220, SPI_MUX_MEZZ_BOT_R},/* 0x2220 - 0x2230  I2C Master OSFP port104 */

    /* MEZZ_TOP_R */
    {0x2240, SPI_MUX_MEZZ_TOP_R},/* 0x2240 - 0x2250  I2C Master OSFP port105 */
    {0x2260, SPI_MUX_MEZZ_TOP_R},/* 0x2260 - 0x2270  I2C Master OSFP port106 */

    /* MB_CPLD1 */
    {0x2380, SPI_MUX_MB_CPLD1},/* 0x2380 - 0x2390  I2C Master OSFP port107 */
    {0x23A0, SPI_MUX_MB_CPLD1},/* 0x23A0 - 0x23B0  I2C Master OSFP port108 */
    {0x23C0, SPI_MUX_MB_CPLD1},/* 0x23C0 - 0x23D0  I2C Master OSFP port109 */
    {0x23E0, SPI_MUX_MB_CPLD1},/* 0x23E0 - 0x23F0  I2C Master OSFP port110 */

    /* MEZZ_BOT_R */
    {0x2240, SPI_MUX_MEZZ_BOT_R},/* 0x2240 - 0x2250  I2C Master OSFP port111 */
    {0x2260, SPI_MUX_MEZZ_BOT_R},/* 0x2260 - 0x2270  I2C Master OSFP port112 */

    /* MEZZ_TOP_R */
    {0x2280, SPI_MUX_MEZZ_TOP_R},/* 0x2280 - 0x2290  I2C Master OSFP port113 */
    {0x22A0, SPI_MUX_MEZZ_TOP_R},/* 0x22A0 - 0x22B0  I2C Master OSFP port114 */

    /* MB_CPLD1 */
    {0x2400, SPI_MUX_MB_CPLD1},/* 0x2400 - 0x2410  I2C Master OSFP port115 */
    {0x2420, SPI_MUX_MB_CPLD1},/* 0x2420 - 0x2430  I2C Master OSFP port116 */
    {0x2440, SPI_MUX_MB_CPLD1},/* 0x2440 - 0x2450  I2C Master OSFP port117 */
    {0x2460, SPI_MUX_MB_CPLD1},/* 0x2460 - 0x2470  I2C Master OSFP port118 */

    /* MEZZ_BOT_R */
    {0x2280, SPI_MUX_MEZZ_BOT_R},/* 0x2280 - 0x2290  I2C Master OSFP port119 */
    {0x22A0, SPI_MUX_MEZZ_BOT_R},/* 0x22A0 - 0x22B0  I2C Master OSFP port120 */

    /* MEZZ_TOP_R */
    {0x22C0, SPI_MUX_MEZZ_TOP_R},/* 0x22C0 - 0x22D0  I2C Master OSFP port121 */
    {0x22E0, SPI_MUX_MEZZ_TOP_R},/* 0x22E0 - 0x22F0  I2C Master OSFP port122 */

    /* MB_CPLD1 */
    {0x2480, SPI_MUX_MB_CPLD1},/* 0x2480 - 0x2490  I2C Master OSFP port123 */
    {0x24A0, SPI_MUX_MB_CPLD1},/* 0x24A0 - 0x24B0  I2C Master OSFP port124 */
    {0x24C0, SPI_MUX_MB_CPLD1},/* 0x24C0 - 0x24D0  I2C Master OSFP port125 */
    {0x24E0, SPI_MUX_MB_CPLD1},/* 0x24E0 - 0x24F0  I2C Master OSFP port126 */

    /* MEZZ_BOT_R */
    {0x22C0, SPI_MUX_MEZZ_BOT_R},/* 0x22C0 - 0x22D0  I2C Master OSFP port127 */
    {0x22E0, SPI_MUX_MEZZ_BOT_R},/* 0x22E0 - 0x22F0  I2C Master OSFP port128 */

    /* MB_CPLD1_SFP */
    {0x2500, SPI_MUX_MB_CPLD1},/* 0x2500 - 0x2510  I2C Master SFP+ port129 */
    {0x2520, SPI_MUX_MB_CPLD1},/* 0x2520 - 0x2530  I2C Master SFP+ port130 */
};

static struct ocores_i2c_platform_data as1813_128o_platform_data = {
    .reg_io_width = 1,
    .reg_shift = 2,
    /*
     * PRER_L and PRER_H are calculated based on clock_khz and bus_khz
     * in i2c-ocores.c:ocores_init.
     * SCL 100KHZ => PRER_L = 0x32, PRER_H = 0x00
     */
    .clock_khz = 25500,
};

struct platform_device *ocore_i2c_device_add(unsigned int id, unsigned long bar_base,
                                             unsigned int offset)
{
    struct resource res = DEFINE_RES_MEM(bar_base + offset, 0x20);
    struct platform_device *pdev;
    int err;

    pdev = platform_device_alloc(OCORES_I2C_DRVNAME, id);
    if (!pdev) {
        err = -ENOMEM;
        pcie_err("Port%u device allocation failed (%d)\n", (id & 0xFF), err);
        goto exit;
    }

    err = platform_device_add_resources(pdev, &res, 1);
    if (err) {
        pcie_err("Port%u device resource addition failed (%d)\n", (id & 0xFF), err);
        goto exit_device_put;
    }

    err = platform_device_add_data(pdev, &as1813_128o_platform_data,
                       sizeof(struct ocores_i2c_platform_data));
    if (err) {
        pcie_err("Port%u platform data allocation failed (%d)\n", (id & 0xFF), err);
        goto exit_device_put;
    }

    err = platform_device_add(pdev);
    if (err) {
        pcie_err("Port%u device addition failed (%d)\n", (id & 0xFF), err);
        goto exit_device_put;
    }

    return pdev;

exit_device_put:
    platform_device_put(pdev);
exit:
    return NULL;
}

static int as1813_128o_pcie_fpga_stat_probe(struct platform_device *pdev)
{
    struct device *dev = &pdev->dev;
    struct as1813_128o_fpga_data *fpga_ctl;
    struct pci_dev *pcidev;
    int i;
    int status = 0, err = 0;
    unsigned long bar_base;

    fpga_ctl = devm_kzalloc(dev, sizeof(struct as1813_128o_fpga_data), GFP_KERNEL);
    if (!fpga_ctl) {
        return -ENOMEM;
    }
    platform_set_drvdata(pdev, fpga_ctl);

    pcidev = pci_get_device(FPGA_PCI_VENDOR_ID, FPGA_PCI_DEVICE_ID, NULL);
     if (!pcidev) {
        dev_err(dev, "Cannot found PCI device(%x:%x)\n",
                     FPGA_PCI_VENDOR_ID, FPGA_PCI_DEVICE_ID);
        return -ENODEV;
    }
    fpga_ctl->pci_fpga_dev.pci_dev = pcidev;

    err = pci_enable_device(pcidev);
    if (err != 0) {
        dev_err(dev, "Cannot enable PCI device(%x:%x)\n",
                     FPGA_PCI_VENDOR_ID, FPGA_PCI_DEVICE_ID);
        status = -ENODEV;
        goto exit_pci_disable;
    }
    /* enable PCI bus-mastering */
    pci_set_master(pcidev);

    fpga_ctl->pci_fpga_dev.data_base_addr0 = pci_iomap(pcidev, BAR0_NUM, 0);
    if (fpga_ctl->pci_fpga_dev.data_base_addr0 == NULL) {
        dev_err(dev, "Failed to map BAR0\n");
        status = -EIO;
        goto exit_pci_disable;
    }

    spi_busy_reg = fpga_ctl->pci_fpga_dev.data_base_addr0 + SPI_BUSY_REG;
    spi_mux_reg = fpga_ctl->pci_fpga_dev.data_base_addr0 + SPI_MUX_REG;

    /* Create I2C ocore devices first, then create the FPGA sysfs.
     * To prevent the application from accessing an ocore device
     * that has not been fully created due to the port status
     * being present.
     */

    /*
     * Create ocore_i2c device for OSFP EEPROM
     */
    bar_base = pci_resource_start(pcidev, BAR0_NUM);
    for (i = 0; i < PORT_NUM; i++) {
        iowrite8(port[i].spi_mux, spi_mux_reg);

        fpga_ctl->pci_fpga_dev.fpga_i2c[i] =
            ocore_i2c_device_add(i, bar_base, port[i].offset);
        if (IS_ERR(fpga_ctl->pci_fpga_dev.fpga_i2c[i])) {
            status = PTR_ERR(fpga_ctl->pci_fpga_dev.fpga_i2c[i]);
            dev_err(dev, "rc:%d, unload Port%u[0x%ux] device\n",
                         status, i, port[i].offset);
            goto exit_ocores_device;
        }
    }

    status = sysfs_create_group(&pdev->dev.kobj, &fpga_port_stat_group);
    if (status) {
        goto exit_ocores_device;
    }

    return 0;

exit_ocores_device:
    while (i > 0) {
        i--;
        platform_device_unregister(fpga_ctl->pci_fpga_dev.fpga_i2c[i]);
    }
exit_pci_iounmap0:
    spi_busy_reg = NULL;
    pci_iounmap(fpga_ctl->pci_fpga_dev.pci_dev, fpga_ctl->pci_fpga_dev.data_base_addr0);
exit_pci_disable:
    pci_disable_device(fpga_ctl->pci_fpga_dev.pci_dev);

    return status;
}

static int as1813_128o_pcie_fpga_stat_remove(struct platform_device *pdev)
{
    struct as1813_128o_fpga_data *fpga_ctl = platform_get_drvdata(pdev);

    if (pci_is_enabled(fpga_ctl->pci_fpga_dev.pci_dev)) {
        int i;

        sysfs_remove_group(&pdev->dev.kobj, &fpga_port_stat_group);
        /* Unregister ocore_i2c device */
        for (i = 0; i < PORT_NUM; i++) {
            platform_device_unregister(fpga_ctl->pci_fpga_dev.fpga_i2c[i]);
        }
        spi_busy_reg = NULL;
        pci_iounmap(fpga_ctl->pci_fpga_dev.pci_dev, fpga_ctl->pci_fpga_dev.data_base_addr0);
        pci_disable_device(fpga_ctl->pci_fpga_dev.pci_dev);
    }

    return 0;
}

static struct platform_driver pcie_fpga_port_stat_driver = {
    .probe      = as1813_128o_pcie_fpga_stat_probe,
    .remove     = as1813_128o_pcie_fpga_stat_remove,
    .driver     = {
        .owner = THIS_MODULE,
        .name  = DRVNAME,
    },
};

static int __init as1813_128o_pcie_fpga_init(void)
{
    int status = 0;

    /*
     * Create FPGA platform driver and device
     */
    status = platform_driver_register(&pcie_fpga_port_stat_driver);
    if (status < 0) {
        return status;
    }

    pdev = platform_device_register_simple(DRVNAME, -1, NULL, 0);
    if (IS_ERR(pdev)) {
        status = PTR_ERR(pdev);
        goto exit_pci;
    }

    return status;

exit_pci:
    platform_driver_unregister(&pcie_fpga_port_stat_driver);

    return status;
}

static void __exit as1813_128o_pcie_fpga_exit(void)
{
    platform_device_unregister(pdev);
    platform_driver_unregister(&pcie_fpga_port_stat_driver);
}


module_init(as1813_128o_pcie_fpga_init);
module_exit(as1813_128o_pcie_fpga_exit);

MODULE_AUTHOR("Eric Yang <eric_yang@accton.com>");
MODULE_DESCRIPTION("AS1813-128O FPGA via PCIE");
MODULE_LICENSE("GPL");
